-- ============================================================================
-- P3-S9-1 : Migration des QUESTIONS vers Supabase (source : src/data)
-- Modèle : 1 ligne par question (item) — 197 questions attendues.
-- question_id = clé racine de persistance (mcq:* / b7:* / b8:*) : les clés de
-- réponses P3-S8 (ex: b7:<case>:<dim>) se dérivent du racine + champs du
-- content et NE DOIVENT JAMAIS être renommées (compatibilité historique).
-- Idempotent : TRUNCATE du contenu avant re-seed (aucune table de réponses
-- touchée). À exécuter dans le SQL Editor (sonylnjcekfxdnhmfkll).
-- ============================================================================

create table if not exists public.assessment_questions (
  id             uuid primary key default gen_random_uuid(),
  assessment_id  text not null,
  battery_id     int  not null,
  question_id    text not null,
  content        jsonb not null,
  display_order  int  not null,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'assessment_questions_key_unique'
  ) then
    alter table public.assessment_questions
      add constraint assessment_questions_key_unique unique (assessment_id, question_id);
  end if;
end $$;

create index if not exists assessment_questions_battery_idx
  on public.assessment_questions (battery_id, display_order);

do $$ begin
  if not exists (select 1 from pg_proc where proname = 'set_updated_at') then
    create function public.set_updated_at() returns trigger
    language plpgsql as $fn$
    begin
      new.updated_at = now();
      return new;
    end;
    $fn$;
  end if;

  if not exists (
    select 1 from pg_trigger where tgname = 'assessment_questions_set_updated_at'
  ) then
    create trigger assessment_questions_set_updated_at
      before update on public.assessment_questions
      for each row execute function public.set_updated_at();
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- Seed déterministe (généré par scripts/generate-p3s9-seed.mjs)
-- 197 questions — 299 clés de réponses dérivables
-- ---------------------------------------------------------------------------
truncate table public.assessment_questions;

insert into public.assessment_questions
  (assessment_id, battery_id, question_id, content, display_order)
values
  ('ntc-assessment', 1, 'mcq:Q1', '{"id":"Q1","dim":"LI","text":"Observez la série : 3, 6, 11, 18, 27, ... Quel est le prochain nombre ?","o":{"A":"36","B":"38","C":"34","D":"40"},"c":"B"}'::jsonb, 1),
  ('ntc-assessment', 1, 'mcq:Q2', '{"id":"Q2","dim":"LI","text":"Dans une équipe SDR, les 5 meilleurs performeurs font tous un débrief de 10 minutes après chaque appel raté. Les 5 moins performants ne le font jamais. Quelle conclusion peut-on tirer avec le plus de certitude ?","o":{"A":"Le débrief après échec cause la performance","B":"Il existe une corrélation entre débrief post-échec et performance, sans preuve de causalité","C":"Les moins performants n''ont pas le temps de débriefer","D":"Le débrief est inutile pour les meilleurs performeurs"},"c":"B"}'::jsonb, 2),
  ('ntc-assessment', 1, 'mcq:Q3', '{"id":"Q3","dim":"LI","text":"Quelle lettre complète la série : B, D, G, K, P, ... ?","o":{"A":"U","B":"V","C":"T","D":"S"},"c":"B"}'::jsonb, 3),
  ('ntc-assessment', 1, 'mcq:Q4', '{"id":"Q4","dim":"LI","text":"Sur les 6 derniers mois, chaque hausse du prix du call center de plus de 15 % a été suivie d''une hausse de la résiliation client le mois suivant. Une hausse de 20 % est prévue le mois prochain. Quelle est la conclusion la plus rigoureuse ?","o":{"A":"Le taux de résiliation va certainement augmenter","B":"Il est probable, sur la base du passé, que le taux de résiliation augmente — sans certitude","C":"Aucune conclusion n''est possible avec seulement 6 mois de données","D":"Le prix n''a aucun lien avec la résiliation"},"c":"B"}'::jsonb, 4),
  ('ntc-assessment', 1, 'mcq:Q5', '{"id":"Q5","dim":"LD","text":"Tous les formateurs certifiés NTC ont suivi le module Savoir-être. Rindra n''a pas suivi le module Savoir-être. Que peut-on en conclure ?","o":{"A":"Rindra n''est pas formateur certifié NTC","B":"Rindra est en cours de certification","C":"On ne peut rien conclure","D":"Rindra a suivi un autre module équivalent"},"c":"A"}'::jsonb, 5),
  ('ntc-assessment', 1, 'mcq:Q6', '{"id":"Q6","dim":"LD","text":"Si un candidat rate le test de logique, il ne passe pas à l''entretien final. Andry est passé à l''entretien final. Qu''est-ce que cela implique nécessairement ?","o":{"A":"Andry a eu une bonne note partout","B":"Andry n''a pas raté le test de logique","C":"Andry a été recommandé par un manager","D":"Rien ne peut être déduit"},"c":"B"}'::jsonb, 6),
  ('ntc-assessment', 1, 'mcq:Q7', '{"id":"Q7","dim":"LD","text":"Trois règles : (1) Si un poste est en télétravail, il n''y a pas de prime de transport. (2) Tous les postes SDR sont en présentiel. (3) Hery occupe un poste SDR. Que peut-on déduire sur la prime de transport de Hery ?","o":{"A":"Il n''y en a pas","B":"Il y en a une","C":"Impossible à déterminer avec ces informations","D":"Cela dépend de son ancienneté"},"c":"C"}'::jsonb, 7),
  ('ntc-assessment', 1, 'mcq:Q8', '{"id":"Q8","dim":"LD","text":"Aucun membre de l''équipe Nexum ne peut être formateur chez NTC en même temps. Fara est formatrice chez NTC. Que peut-on affirmer avec certitude sur Fara ?","o":{"A":"Elle n''appartient pas à l''équipe Nexum","B":"Elle va bientôt rejoindre Nexum","C":"Elle a travaillé chez Nexum par le passé","D":"Rien ne peut être affirmé"},"c":"A"}'::jsonb, 8),
  ('ntc-assessment', 1, 'mcq:Q9', '{"id":"Q9","dim":"LA","text":"Si la séquence de symboles ♦●♦ devient ●♦● selon une règle constante, que devient ♦♦●♦ selon la même règle ?","o":{"A":"●●♦●","B":"●♦♦●","C":"♦●●♦","D":"●●●♦"},"c":"A"}'::jsonb, 9),
  ('ntc-assessment', 1, 'mcq:Q10', '{"id":"Q10","dim":"LA","text":"La séquence suit deux règles alternées : 2, 5, 4, 10, 8, 20, 16, ... Quel est le prochain terme ?","o":{"A":"32","B":"40","C":"24","D":"22"},"c":"B"}'::jsonb, 10),
  ('ntc-assessment', 1, 'mcq:Q11', '{"id":"Q11","dim":"LA","text":"Dans un système où A=1, B=2 ... Z=26, et où le score d''un mot = somme des positions des lettres divisée par le nombre de lettres, quel est le score du mot « CDE » ?","o":{"A":"3","B":"4","C":"5","D":"6"},"c":"B"}'::jsonb, 11),
  ('ntc-assessment', 1, 'mcq:Q12', '{"id":"Q12","dim":"LA","text":"Une règle transforme des couples de nombres : (2,3)→5, (4,1)→5, (6,7)→13, (3,3)→6. Quelle règle est appliquée, et quel est le résultat pour (5,9) ?","o":{"A":"Addition, résultat 14","B":"Multiplication, résultat 45","C":"Différence, résultat 4","D":"Moyenne, résultat 7"},"c":"A"}'::jsonb, 12),
  ('ntc-assessment', 1, 'mcq:Q13', '{"id":"Q13","dim":"ES","text":"Un manager reçoit trois informations séparées : (1) l''absentéisme du lundi est 3x supérieur, (2) les formateurs du lundi matin sont toujours les mêmes deux personnes, (3) ces deux formateurs veulent plus de flexibilité. Quelle synthèse la plus utile peut-il en tirer ?","o":{"A":"Trois faits séparés sans lien direct","B":"Le planning du lundi matin doit être questionné en priorité","C":"Il faut sanctionner l''absentéisme du lundi","D":"Il faut remplacer les deux formateurs"},"c":"B"}'::jsonb, 13),
  ('ntc-assessment', 1, 'mcq:Q14', '{"id":"Q14","dim":"ES","text":"Un rapport trimestriel indique : le CA a augmenté de 12 %, la marge a baissé de 4 points, et 3 des 5 nouveaux clients ont été acquis via des remises exceptionnelles. Quelle phrase résume le mieux la situation ?","o":{"A":"Le trimestre est excellent, le CA progresse fortement","B":"La croissance du CA masque une dégradation de la rentabilité, en partie tirée par des remises non pérennes","C":"La marge baisse à cause d''une mauvaise gestion des coûts","D":"Il faut arrêter d''acquérir de nouveaux clients"},"c":"B"}'::jsonb, 14),
  ('ntc-assessment', 1, 'mcq:Q15', '{"id":"Q15","dim":"ES","text":"Cinq collaborateurs mentionnent indépendamment, sur des sujets différents, le mot « incertitude » en entretien annuel. Quelle est la synthèse la plus rigoureuse ?","o":{"A":"C''est une coïncidence sans signification","B":"Un climat d''incertitude commun mérite d''être creusé, même si les sujets diffèrent en surface","C":"Ces cinq personnes devraient être recadrées","D":"Le vocabulaire n''a pas d''importance en entretien"},"c":"B"}'::jsonb, 15),
  ('ntc-assessment', 1, 'mcq:Q16', '{"id":"Q16","dim":"ES","text":"Trois retours contradictoires sur un stagiaire : formateur « brillant mais dispersé », pair « fiable et discret », lui-même « perfectionniste ». Proposez en 2-3 phrases une synthèse intégrant les trois retours.","open":true,"guidance":"Score élevé si la réponse relie les trois angles par une explication cohérente. Score faible si simple juxtaposition."}'::jsonb, 16),
  ('ntc-assessment', 1, 'mcq:Q17', '{"id":"Q17","dim":"CA","text":"Le taux de conversion d''une équipe SDR a chuté de 22 % à 14 % en un mois. Quatre hypothèses possibles. Quelle est la première étape analytique la plus rigoureuse ?","o":{"A":"Choisir l''hypothèse la plus probable intuitivement et agir dessus","B":"Isoler chaque variable en comparant les sous-groupes concernés avant de conclure","C":"Changer le script immédiatement par précaution","D":"Attendre le mois suivant pour voir si ça se reproduit"},"c":"B"}'::jsonb, 17),
  ('ntc-assessment', 1, 'mcq:Q18', '{"id":"Q18","dim":"CA","text":"Un candidat a un score cognitif élevé mais un score d''exécution faible. Quelle question différencie le mieux un problème de compétence d''un problème de motivation ?","o":{"A":"« Est-ce qu''il est intelligent ? »","B":"« Produit-il des résultats constants quand la tâche est cadrée et suivie, ou seulement quand elle est libre ? »","C":"« Est-ce qu''il aime son travail ? »","D":"« A-t-il déjà échoué dans le passé ? »"},"c":"B"}'::jsonb, 18),
  ('ntc-assessment', 1, 'mcq:Q19', '{"id":"Q19","dim":"CA","text":"Un module de formation a un taux d''abandon de 40 % contre 10 % ailleurs. Quelle démarche décompose le mieux le problème ?","o":{"A":"Interroger uniquement les abandons","B":"Comparer le profil des abandons vs non-abandons sur plusieurs variables avant de conclure","C":"Supprimer le module","D":"Demander au formateur son avis et s''arrêter là"},"c":"B"}'::jsonb, 19),
  ('ntc-assessment', 1, 'mcq:Q20', '{"id":"Q20","dim":"RM","text":"23 + 48 − 15 = ?","o":{"A":"56","B":"66","C":"46","D":"58"},"c":"A"}'::jsonb, 20),
  ('ntc-assessment', 1, 'mcq:Q21', '{"id":"Q21","dim":"RM","text":"Un appel dure en moyenne 4 minutes. Un conseiller enchaîne 12 appels. Combien de temps au total ?","o":{"A":"44","B":"48","C":"52","D":"36"},"c":"B"}'::jsonb, 21),
  ('ntc-assessment', 1, 'mcq:Q22', '{"id":"Q22","dim":"RM","text":"Quel mot n''appartient pas à la série : Empathie, Écoute, Facturation, Diplomatie ?","o":{"A":"Empathie","B":"Écoute","C":"Facturation","D":"Diplomatie"},"c":"C"}'::jsonb, 22),
  ('ntc-assessment', 1, 'mcq:Q23', '{"id":"Q23","dim":"RM","text":"Combien de lettres dans le mot « FORMATION » ?","o":{"A":"8","B":"9","C":"10","D":"11"},"c":"B"}'::jsonb, 23),
  ('ntc-assessment', 1, 'mcq:Q24', '{"id":"Q24","dim":"VS","text":"Augmenter le nombre d''apprenants par session réduit le coût par apprenant, mais un formateur signale que l''attention individuelle baisse, ce qui augmente l''échec au test final, ce qui augmente les sessions de rattrapage. Quel est l''effet système le plus probable sur le coût réel par diplômé ?","o":{"A":"Il baisse, comme prévu","B":"Il peut in fine augmenter, la boucle de rattrapage annulant l''économie initiale","C":"Il reste stable","D":"Il n''y a pas de lien"},"c":"B"}'::jsonb, 24),
  ('ntc-assessment', 1, 'mcq:Q25', '{"id":"Q25","dim":"VS","text":"Une agence de placement augmente ses commissions de mise en relation. Quel effet secondaire faut-il anticiper avant de valider cette décision ?","o":{"A":"Aucun","B":"L''effet sur la sélectivité des candidats si la pression au placement rapide augmente","C":"Un effet uniquement sur la trésorerie court terme","D":"Un effet uniquement sur l''image de marque"},"c":"B"}'::jsonb, 25),
  ('ntc-assessment', 1, 'mcq:Q26', '{"id":"Q26","dim":"VS","text":"Décrivez en 2-3 phrases une boucle de rétroaction observée dans un contexte professionnel, en identifiant la variable qui s''auto-renforce ou s''auto-régule.","open":true,"guidance":"Score élevé si une véritable boucle est décrite. Score faible si simple cause à effet linéaire présentée comme une boucle."}'::jsonb, 26),
  ('ntc-assessment', 1, 'mcq:Q27', '{"id":"Q27","dim":"IS","text":"Un concurrent direct annonce un partenariat avec une grande entreprise cliente. Quelle réaction traduit le mieux une intelligence stratégique ?","o":{"A":"Baisser immédiatement ses prix","B":"Analyser ce que ce partenariat révèle des besoins non couverts par le concurrent, et positionner son offre sur cet angle mort","C":"Ignorer l''annonce","D":"Communiquer publiquement contre le concurrent"},"c":"B"}'::jsonb, 27),
  ('ntc-assessment', 1, 'mcq:Q28', '{"id":"Q28","dim":"IS","text":"Un partenaire propose un financement important en échange d''un droit de regard sur les recrutements. Quelle question doit primer avant toute négociation de détail ?","o":{"A":"Le montant est-il suffisant ?","B":"Ce droit de regard menace-t-il la souveraineté de décision à long terme, indépendamment du montant ?","C":"Le partenaire est-il connu ?","D":"Combien de temps prendra la négociation ?"},"c":"B"}'::jsonb, 28),
  ('ntc-assessment', 1, 'mcq:Q29', '{"id":"Q29","dim":"IS","text":"Entre un contrat très rentable avec un seul client (70 % du CA futur) ou deux contrats moins rentables avec des clients différents, quel raisonnement prime ?","o":{"A":"Toujours prendre le plus rentable","B":"Le risque de dépendance doit être mis en balance avec le gain de rentabilité","C":"Prendre les deux sans évaluation","D":"Refuser les deux"},"c":"B"}'::jsonb, 29),
  ('ntc-assessment', 1, 'mcq:Q30', '{"id":"Q30","dim":"CD","text":"Un centre de formation double ses effectifs en 6 mois sans augmenter le nombre de formateurs. Quelle conséquence à moyen terme est la plus probable ?","o":{"A":"Aucune","B":"Une dégradation progressive de la qualité perçue, avec un effet retardé sur la réputation","C":"Une amélioration de la rentabilité sans autre effet","D":"Un effet uniquement positif sur la motivation"},"c":"B"}'::jsonb, 30),
  ('ntc-assessment', 1, 'mcq:Q31', '{"id":"Q31","dim":"CD","text":"Un partenaire impose ses propres outils de suivi pédagogique. Quel risque anticiper dans 12 mois si cette double gestion n''est pas résolue ?","o":{"A":"Aucun risque particulier","B":"Une dette organisationnelle (double saisie, données non réconciliées) plus coûteuse à corriger tardivement","C":"Un gain de temps immédiat et durable","D":"Un renforcement automatique de la qualité des données"},"c":"B"}'::jsonb, 31),
  ('ntc-assessment', 1, 'mcq:Q32', '{"id":"Q32","dim":"CD","text":"Une nouvelle offre rencontre un succès immédiat dépassant les prévisions. Quels sont les deux premiers risques à anticiper avant de célébrer ?","open":true,"guidance":"Score élevé si tensions de second ordre anticipées (capacité, qualité, trésorerie, délais). Score faible si aucun risque identifié."}'::jsonb, 32),
  ('ntc-assessment', 2, 'mcq:V1', '{"id":"V1","dim":"INT","text":"Vous découvrez qu''un collaborateur très performant a triché pour atteindre ses objectifs. Que faites-vous ?","o":{"A":"Je le protège, ses résultats sont trop précieux.","B":"J''enquête discrètement avant toute décision.","C":"Je l''écarte immédiatement, sans exception.","D":"J''évalue les conséquences réelles avant de trancher."},"w":{"A":[["LOY",3],["INT",-1]],"B":[["JUS",2],["PRA",1]],"C":[["INT",3],["RIG",1],["COU",2]],"D":[["PRA",3],["UTI",1]]}}'::jsonb, 33),
  ('ntc-assessment', 2, 'mcq:V2', '{"id":"V2","dim":"INT","text":"Un collaborateur vous demande de valider une dépense légèrement au-dessus du plafond, « tout le monde le fait ». Vous :","o":{"A":"Validez, pour ne pas casser la dynamique.","B":"Refusez et rappelez la règle.","C":"Refusez et ouvrez une revue des dépenses récentes.","D":"Validez cette fois, mais fixez une limite claire."},"w":{"A":[["INT",-1],["LOY",1]],"B":[["INT",2],["PRA",1]],"C":[["INT",3],["JUS",1],["RIG",1]],"D":[["PRA",3],["UTI",2]]}}'::jsonb, 34),
  ('ntc-assessment', 2, 'mcq:V3', '{"id":"V3","dim":"INT","text":"Un rapport que vous devez signer contient un chiffre arrondi favorablement, mais pas franchement faux. Vous :","o":{"A":"Signez, l''écart est mineur.","B":"Corrigez avant de signer, même si ça retarde l''envoi.","C":"Signez, mais informez discrètement votre hiérarchie.","D":"Refusez de signer tant que ce n''est pas recalculé."},"w":{"A":[["INT",-1],["PRA",1]],"B":[["INT",3]],"C":[["INT",2],["LOY",2]],"D":[["INT",3],["RIG",1]]}}'::jsonb, 35),
  ('ntc-assessment', 2, 'mcq:V4', '{"id":"V4","dim":"INT","text":"Un client vous demande de présenter un résultat de formation plus favorablement qu''il ne l''est. Vous :","o":{"A":"Acceptez, pratique commerciale courante.","B":"Proposez une présentation honnête valorisant les vrais points positifs.","C":"Refusez catégoriquement toute reformulation.","D":"Acceptez partiellement, en gardant une trace écrite de la vérité en interne."},"w":{"A":[["INT",-3],["PRA",3]],"B":[["INT",3],["PRA",2]],"C":[["INT",3],["RIG",1]],"D":[["INT",-2],["PRA",3],["UTI",1]]}}'::jsonb, 36),
  ('ntc-assessment', 2, 'mcq:V5', '{"id":"V5","dim":"LOY","text":"Votre direction prend une décision avec laquelle vous êtes en désaccord profond, mais légale et non dangereuse. Devant votre équipe, vous :","o":{"A":"Exprimez ouvertement votre désaccord.","B":"Défendez la décision publiquement, désaccord exprimé en privé à la direction.","C":"Restez neutre.","D":"Appliquez sans commentaire, quoi qu''il en coûte."},"w":{"A":[["LOY",-2],["COU",1]],"B":[["LOY",3],["COU",2]],"C":[["LOY",1],["PRA",1]],"D":[["LOY",3],["RIG",2]]}}'::jsonb, 37),
  ('ntc-assessment', 2, 'mcq:V6', '{"id":"V6","dim":"LOY","text":"Un ancien collègue, parti chez un concurrent, vous propose de partager des informations sensibles « entre amis ». Vous :","o":{"A":"Acceptez un échange limité.","B":"Refusez fermement et coupez ce type d''échange.","C":"Refusez, mais continuez la relation personnelle normalement.","D":"Acceptez pour obtenir des informations en retour."},"w":{"A":[["LOY",-1],["INT",-1]],"B":[["LOY",3],["INT",3]],"C":[["LOY",2],["INT",2]],"D":[["LOY",-3],["INT",-1],["PRA",-1]]}}'::jsonb, 38),
  ('ntc-assessment', 2, 'mcq:V7', '{"id":"V7","dim":"LOY","text":"Un pair que vous appréciez cherche discrètement un poste ailleurs alors qu''il est sur un projet critique. Vous :","o":{"A":"Le couvrez, ça ne regarde que lui.","B":"L''encouragez à en parler lui-même à son manager rapidement.","C":"Prévenez directement le manager sans lui en parler d''abord.","D":"Ne faites rien."},"w":{"A":[["LOY",3],["INT",-2]],"B":[["LOY",1],["COU",1]],"C":[["LOY",3],["JUS",2]],"D":[["PRA",-1]]}}'::jsonb, 39),
  ('ntc-assessment', 2, 'mcq:V8', '{"id":"V8","dim":"LOY","text":"Votre équipe est critiquée injustement par un autre département devant la direction générale. Vous :","o":{"A":"Défendez votre équipe immédiatement et fermement.","B":"Demandez à recueillir les faits avant de répondre publiquement.","C":"Laissez faire, la vérité finira par ressortir.","D":"Défendez votre équipe en privé après coup."},"w":{"A":[["LOY",3],["COU",3],["RIG",1]],"B":[["LOY",2],["JUS",3],["PRA",1]],"C":[["LOY",-2],["PRA",-1]],"D":[["LOY",2],["COU",-2]]}}'::jsonb, 40),
  ('ntc-assessment', 2, 'mcq:V9', '{"id":"V9","dim":"JUS","text":"Deux collaborateurs ont commis la même erreur. L''un est performeur historique, l''autre nouveau en période d''essai. Vous :","o":{"A":"Sanctionnez les deux de la même façon.","B":"Êtes plus indulgent avec le performeur historique.","C":"Êtes plus sévère avec le nouveau.","D":"Évaluez chaque situation selon son contexte propre."},"w":{"A":[["JUS",3],["RIG",2]],"B":[["JUS",-2],["PRA",1]],"C":[["JUS",-2]],"D":[["JUS",3],["PRA",2]]}}'::jsonb, 41),
  ('ntc-assessment', 2, 'mcq:V10', '{"id":"V10","dim":"JUS","text":"Répartition de primes à budget limité : effort fourni ou résultats obtenus ? Vous :","o":{"A":"Récompensez uniquement les résultats.","B":"Récompensez uniquement l''effort.","C":"Pondérez les deux selon une grille explicite communiquée à l''avance.","D":"Décidez au cas par cas, selon votre ressenti."},"w":{"A":[["JUS",2],["PRA",1]],"B":[["JUS",2]],"C":[["JUS",3],["RIG",1]],"D":[["JUS",-2],["PRA",2]]}}'::jsonb, 42),
  ('ntc-assessment', 2, 'mcq:V11', '{"id":"V11","dim":"JUS","text":"Un senior bénéficie d''un avantage informel que les nouveaux n''ont pas. Un nouveau le questionne. Vous :","o":{"A":"Maintenez l''avantage du senior sans l''étendre.","B":"Étendez l''avantage à tous selon des critères objectifs.","C":"Supprimez l''avantage pour éviter toute inégalité perçue.","D":"Expliquez le contexte historique sans rien changer."},"w":{"A":[["JUS",-2],["PRA",1]],"B":[["JUS",3]],"C":[["JUS",2],["RIG",2]],"D":[["JUS",-1],["PRA",2]]}}'::jsonb, 43),
  ('ntc-assessment', 2, 'mcq:V12', '{"id":"V12","dim":"JUS","text":"Respecter à la lettre une règle stricte, ou faire une exception justifiée par une situation humaine exceptionnelle ? Vous :","o":{"A":"Appliquez la règle sans exception.","B":"Faites l''exception, la situation humaine prime.","C":"Faites l''exception mais la documentez pour qu''elle reste isolée.","D":"Remontez la décision à un niveau supérieur."},"w":{"A":[["JUS",1],["RIG",3]],"B":[["JUS",1],["PRA",3]],"C":[["JUS",1],["PRA",2]],"D":[["COU",-2]]}}'::jsonb, 44),
  ('ntc-assessment', 2, 'mcq:V13', '{"id":"V13","dim":"PRA","text":"Une solution élégante prend 3 mois ; une solution imparfaite mais fonctionnelle existe en 1 semaine. Vous :","o":{"A":"Choisissez systématiquement la solution élégante.","B":"Choisissez la solution rapide, quitte à l''améliorer plus tard.","C":"Évaluez le coût réel de l''attente avant de choisir.","D":"Cherchez un compromis à mi-chemin."},"w":{"A":[["PRA",-2],["RIG",1]],"B":[["PRA",3],["UTI",2]],"C":[["PRA",3]],"D":[["PRA",2]]}}'::jsonb, 45),
  ('ntc-assessment', 2, 'mcq:V14', '{"id":"V14","dim":"PRA","text":"Un principe personnel entre en conflit avec un résultat business important à court terme. Vous :","o":{"A":"Le principe prime toujours.","B":"Le résultat business prime.","C":"Vous cherchez une troisième option qui ne sacrifie ni l''un ni l''autre.","D":"Vous acceptez un compromis partiel, assumé et limité dans le temps."},"w":{"A":[["PRA",-3],["RIG",3]],"B":[["PRA",3]],"C":[["PRA",3],["CA",1]],"D":[["PRA",2]]}}'::jsonb, 46),
  ('ntc-assessment', 2, 'mcq:V15', '{"id":"V15","dim":"PRA","text":"Un processus obligatoire ralentit le travail sans bénéfice clair. Vous :","o":{"A":"Le respectez à la lettre.","B":"Le contournez discrètement.","C":"Proposez officiellement de le faire évoluer, en argumentant.","D":"L''ignorez ouvertement et assumez la responsabilité."},"w":{"A":[["PRA",-2],["RIG",2]],"B":[["PRA",2],["INT",-1]],"C":[["PRA",3],["COU",2]],"D":[["COU",3],["PRA",2]]}}'::jsonb, 47),
  ('ntc-assessment', 2, 'mcq:V16', '{"id":"V16","dim":"PRA","text":"Méthode « by the book » recommandée, ou méthode alternative que votre expérience terrain dit plus efficace ici ? Vous :","o":{"A":"Suivez toujours la méthode officielle.","B":"Suivez votre expérience terrain.","C":"Testez les deux sur un petit périmètre avant de trancher.","D":"Suivez la méthode officielle mais remontez votre retour d''expérience."},"w":{"A":[["PRA",-1],["RIG",2]],"B":[["PRA",3]],"C":[["PRA",3],["CA",1]],"D":[["PRA",2],["LOY",2]]}}'::jsonb, 48),
  ('ntc-assessment', 2, 'mcq:V17', '{"id":"V17","dim":"UTI","text":"Une décision profite à 80 % de l''équipe mais désavantage clairement les 20 % restants. Vous :","o":{"A":"Prenez la décision qui profite au plus grand nombre.","B":"Cherchez une compensation spécifique pour les 20 % désavantagés.","C":"Renoncez tant qu''une solution unanime n''est pas trouvée.","D":"Laissez l''équipe elle-même trancher collectivement."},"w":{"A":[["UTI",3]],"B":[["UTI",2],["JUS",2]],"C":[["UTI",-2],["RIG",1]],"D":[["PRA",2],["COU",-1]]}}'::jsonb, 49),
  ('ntc-assessment', 2, 'mcq:V18', '{"id":"V18","dim":"UTI","text":"Fermer une antenne peu rentable renforcerait l''antenne principale mais laisserait les apprenants engagés sans solution. Vous :","o":{"A":"Fermez rapidement, le bénéfice global prime.","B":"Maintenez l''antenne, l''engagement pris prime.","C":"Fermez, mais après avoir sécurisé une continuité pour chaque apprenant.","D":"Repoussez la décision d''un an."},"w":{"A":[["UTI",3],["COU",2]],"B":[["UTI",-2],["INT",1],["LOY",1]],"C":[["UTI",2],["JUS",3],["PRA",1]],"D":[["PRA",-1]]}}'::jsonb, 50),
  ('ntc-assessment', 2, 'mcq:V19', '{"id":"V19","dim":"UTI","text":"Investir davantage dans les meilleurs éléments génère plus de résultats globaux que répartir également. Vous :","o":{"A":"Concentrez l''investissement sur les meilleurs.","B":"Répartissez équitablement.","C":"Combinez : socle commun + surplus pour les meilleurs.","D":"Investissez selon le potentiel perçu."},"w":{"A":[["UTI",3],["JUS",-2]],"B":[["JUS",3],["UTI",-2]],"C":[["UTI",2],["JUS",2]],"D":[["UTI",2]]}}'::jsonb, 51),
  ('ntc-assessment', 2, 'mcq:V20', '{"id":"V20","dim":"UTI","text":"Un changement de process améliore la productivité globale de 15 % mais rend obsolète une compétence longuement investie par certains. Vous :","o":{"A":"Appliquez le changement, le bénéfice collectif prime.","B":"Retardez le changement pour laisser le temps de se repositionner.","C":"Appliquez en parallèle d''un plan de reconversion dédié.","D":"Renoncez si l''impact humain est trop important."},"w":{"A":[["UTI",3]],"B":[["UTI",-2]],"C":[["UTI",2],["PRA",3],["JUS",2]],"D":[["UTI",-3],["RIG",1]]}}'::jsonb, 52),
  ('ntc-assessment', 2, 'mcq:V21', '{"id":"V21","dim":"RIG","text":"Une règle personnelle stricte causerait un tort disproportionné si suivie à la lettre dans un cas précis. Vous :","o":{"A":"Maintenez la règle sans exception.","B":"Faites une exception ponctuelle, le contexte le justifie.","C":"Reformulez la vérité pour ne pas mentir tout en évitant le tort.","D":"Remettez en question la règle elle-même après coup."},"w":{"A":[["RIG",3],["INT",1]],"B":[["RIG",-2],["PRA",1]],"C":[["RIG",2]],"D":[["RIG",-3]]}}'::jsonb, 53),
  ('ntc-assessment', 2, 'mcq:V22', '{"id":"V22","dim":"RIG","text":"Un collègue demande d''assouplir « juste cette fois » une règle éthique normalement non négociable. Vous :","o":{"A":"Refusez catégoriquement.","B":"Écoutez l''argument, puis décidez selon le mérite du cas.","C":"Acceptez, la relation compte plus dans ce cas précis.","D":"Proposez une alternative qui respecte l''esprit de la règle."},"w":{"A":[["RIG",3],["COU",2]],"B":[["RIG",-2],["JUS",2]],"C":[["RIG",-3],["LOY",-1]],"D":[["RIG",2],["PRA",3]]}}'::jsonb, 54),
  ('ntc-assessment', 2, 'mcq:V23', '{"id":"V23","dim":"RIG","text":"Votre position sur un sujet éthique a évolué depuis 5 ans, sous l''effet de l''expérience. Vous :","o":{"A":"Signe de manque de solidité de vos convictions.","B":"Normal et sain, les convictions s''affinent avec l''expérience.","C":"Revenez consciemment à votre position d''origine, par principe.","D":"Adoptez la nouvelle position sans y réfléchir davantage."},"w":{"A":[["RIG",3]],"B":[["RIG",-2]],"C":[["RIG",3]],"D":[["RIG",-2]]}}'::jsonb, 55),
  ('ntc-assessment', 2, 'mcq:V24', '{"id":"V24","dim":"RIG","text":"Deux principes auxquels vous croyez fermement entrent en contradiction directe. Vous :","o":{"A":"Choisissez celui jugé supérieur en général, de façon constante.","B":"Décidez au cas par cas selon les enjeux spécifiques.","C":"Refusez de trancher et cherchez à éviter la situation.","D":"Établissez une nouvelle règle hiérarchisant les deux principes."},"w":{"A":[["RIG",2]],"B":[["RIG",-3],["PRA",1]],"C":[["COU",-2]],"D":[["RIG",2]]}}'::jsonb, 56),
  ('ntc-assessment', 2, 'mcq:V25', '{"id":"V25","dim":"COU","text":"Vous devez annoncer une décision impopulaire à toute l''équipe, sans possibilité de la nuancer. Vous :","o":{"A":"L''annoncez vous-même, directement.","B":"Demandez à votre manager de l''annoncer à votre place.","C":"L''annoncez en diluant le message.","D":"Retardez l''annonce autant que possible."},"w":{"A":[["COU",3],["INT",2]],"B":[["COU",-3]],"C":[["COU",-2],["PRA",1]],"D":[["COU",-3]]}}'::jsonb, 57),
  ('ntc-assessment', 2, 'mcq:V26', '{"id":"V26","dim":"COU","text":"Désaccord frontal avec une décision de votre supérieur, prise en réunion devant d''autres. Vous :","o":{"A":"Exprimez votre désaccord sur-le-champ, devant tout le monde.","B":"Attendez un moment privé pour exprimer votre désaccord directement.","C":"Vous taisez en réunion et n''en reparlez plus ensuite.","D":"En parlez à des collègues plutôt qu''à votre supérieur."},"w":{"A":[["COU",3]],"B":[["COU",3]],"C":[["COU",-3]],"D":[["COU",-2],["LOY",-1]]}}'::jsonb, 58),
  ('ntc-assessment', 2, 'mcq:V27', '{"id":"V27","dim":"COU","text":"Vous constatez qu''un supérieur commet une erreur aux conséquences sérieuses, mais le lui dire coûte cher relationnellement. Vous :","o":{"A":"Le lui dites clairement, quel qu''en soit le coût.","B":"Le lui dites de façon indirecte et prudente.","C":"Ne dites rien.","D":"En parlez d''abord à quelqu''un d''autre pour évaluer si cela vaut le risque."},"w":{"A":[["COU",3],["INT",2]],"B":[["COU",2]],"C":[["COU",-3]],"D":[["COU",-2],["PRA",1]]}}'::jsonb, 59),
  ('ntc-assessment', 2, 'mcq:V28', '{"id":"V28","dim":"COU","text":"Un projet dans lequel vous avez beaucoup investi montre des signes clairs d''échec. Vous êtes seul à l''avoir remarqué. Vous :","o":{"A":"Le signalez immédiatement, même si cela remet en cause votre travail.","B":"Continuez à y croire un peu plus longtemps.","C":"Attendez que quelqu''un d''autre le remarque en premier.","D":"Le signalez, en minimisant votre propre responsabilité."},"w":{"A":[["COU",3],["INT",3]],"B":[["COU",-1]],"C":[["COU",-3]],"D":[["COU",2],["INT",-1]]}}'::jsonb, 60),
  ('ntc-assessment', 3, 'mcq:D1', '{"id":"D1","dim":"LDD","text":"Vous disposez de trois heures pour sauver un projet en difficulté. Vous choisissez :","o":{"A":"Réunir toute l''équipe pour décider ensemble.","B":"Décider seul et annoncer la marche à suivre.","C":"Collecter encore des informations avant d''agir.","D":"Prioriser les risques et traiter le plus urgent."},"w":{"A":[["CNS",3],["LDD",2]],"B":[["LDD",3],["AUT",3],["CNF",3]],"C":[["RIS",-2],["AUT",1]],"D":[["LDD",2],["RIS",2],["CNF",2]]}}'::jsonb, 61),
  ('ntc-assessment', 3, 'mcq:D2', '{"id":"D2","dim":"LDD","text":"Décision à prendre dans l''heure, deux membres de l''équipe injoignables. Vous :","o":{"A":"Décidez seul, ils seront informés après.","B":"Attendez qu''ils soient joignables, quitte à dépasser le délai.","C":"Décidez avec ceux qui sont présents, en cherchant leur accord.","D":"Demandez à quelqu''un d''autre de trancher à votre place."},"w":{"A":[["LDD",3],["AUT",3]],"B":[["CNS",3],["RIS",-1]],"C":[["CNS",2],["LDD",2]],"D":[["DEL",3],["LDD",-2]]}}'::jsonb, 62),
  ('ntc-assessment', 3, 'mcq:D3', '{"id":"D3","dim":"LDD","text":"On vous confie une décision hors de votre périmètre officiel, mais personne d''autre ne s''en saisit. Vous :","o":{"A":"La prenez, quelqu''un doit le faire.","B":"Attendez qu''on vous la confie formellement.","C":"La signalez à qui de droit sans la prendre vous-même.","D":"La prenez, en informant immédiatement votre hiérarchie."},"w":{"A":[["LDD",3],["AUT",3]],"B":[["LDD",-2]],"C":[["DEL",2],["LDD",-1]],"D":[["LDD",3],["CNF",2]]}}'::jsonb, 63),
  ('ntc-assessment', 3, 'mcq:D4', '{"id":"D4","dim":"LDD","text":"Face à un choix technique que vous ne maîtrisez pas parfaitement, vous :","o":{"A":"Décidez quand même, votre jugement global compense.","B":"Confiez la décision à la personne la plus compétente.","C":"Prenez le temps de vous former avant de trancher.","D":"Décidez avec l''avis d''un expert, mais gardez la décision finale."},"w":{"A":[["CNF",3],["LDD",2],["RIS",2]],"B":[["DEL",3]],"C":[["AUT",2],["RIS",-1]],"D":[["LDD",3],["CNS",1]]}}'::jsonb, 64),
  ('ntc-assessment', 3, 'mcq:D5', '{"id":"D5","dim":"LDD","text":"En réunion, un désaccord bloque la décision depuis 20 minutes. Vous :","o":{"A":"Tranchez vous-même pour débloquer la situation.","B":"Laissez la discussion se poursuivre.","C":"Proposez un vote pour trancher collectivement.","D":"Reportez la décision à une prochaine réunion."},"w":{"A":[["LDD",3],["CNF",3]],"B":[["CNS",2],["LDD",-2]],"C":[["CNS",3],["LDD",1]],"D":[["RIS",-2],["LDD",-1]]}}'::jsonb, 65),
  ('ntc-assessment', 3, 'mcq:D6', '{"id":"D6","dim":"DEL","text":"Une tâche importante : la confier à un junior (risque d''erreur plus élevé) ou la faire vous-même ? Vous :","o":{"A":"La faites vous-même, la sécurité du résultat prime.","B":"La confiez au junior, occasion de le former.","C":"La confiez mais supervisez chaque étape de près.","D":"La confiez avec un point de contrôle à mi-parcours."},"w":{"A":[["DEL",-3],["AUT",3]],"B":[["DEL",3],["RIS",2]],"C":[["DEL",1],["CNF",-1]],"D":[["DEL",2],["CNF",2]]}}'::jsonb, 66),
  ('ntc-assessment', 3, 'mcq:D7', '{"id":"D7","dim":"DEL","text":"Vous partez en congé une semaine, période chargée. Vous :","o":{"A":"Préparez un plan détaillé étape par étape.","B":"Laissez le remplaçant s''organiser à sa façon.","C":"Restez joignable en continu pour valider chaque décision.","D":"Reportez les décisions importantes à votre retour."},"w":{"A":[["DEL",2]],"B":[["DEL",3],["CNF",3]],"C":[["DEL",-3]],"D":[["LDD",-1],["RIS",-2]]}}'::jsonb, 67),
  ('ntc-assessment', 3, 'mcq:D8', '{"id":"D8","dim":"DEL","text":"Un collaborateur demande plus de responsabilités. Vous :","o":{"A":"Lui en confiez immédiatement.","B":"Attendez plus de preuves de fiabilité.","C":"Lui en confiez progressivement, avec des jalons clairs.","D":"Refusez pour l''instant."},"w":{"A":[["DEL",3],["RIS",2]],"B":[["DEL",-2]],"C":[["DEL",2]],"D":[["DEL",-3]]}}'::jsonb, 68),
  ('ntc-assessment', 3, 'mcq:D9', '{"id":"D9","dim":"DEL","text":"Répartir un projet complexe entre trois personnes d''expérience inégale. Vous :","o":{"A":"Confiez les parties critiques à la plus expérimentée seulement.","B":"Répartissez équitablement.","C":"Confiez selon les forces de chacun, résultat hétérogène accepté.","D":"Gardez les parties critiques pour vous-même."},"w":{"A":[["DEL",2],["RIS",-2]],"B":[["DEL",3],["RIS",3]],"C":[["DEL",3]],"D":[["DEL",-3],["AUT",3]]}}'::jsonb, 69),
  ('ntc-assessment', 3, 'mcq:D10', '{"id":"D10","dim":"DEL","text":"Une décision déléguée produit un résultat différent de ce que vous auriez choisi, mais défendable. Vous :","o":{"A":"La validez telle quelle.","B":"La corrigez pour qu''elle corresponde à votre choix.","C":"En discutez avec lui pour comprendre son raisonnement.","D":"La validez, mais l''ajustez légèrement sans lui en parler."},"w":{"A":[["DEL",3],["CNF",3]],"B":[["DEL",-3]],"C":[["DEL",2],["CNS",1]],"D":[["DEL",-2],["CNF",-1]]}}'::jsonb, 70),
  ('ntc-assessment', 3, 'mcq:D11', '{"id":"D11","dim":"AUT","text":"Décision importante sans règle ni précédent pour vous guider. Vous :","o":{"A":"Décidez sur votre propre jugement, sans validation.","B":"Cherchez l''avis de plusieurs personnes avant de trancher.","C":"Cherchez un précédent comparable ailleurs.","D":"Attendez qu''une règle soit établie."},"w":{"A":[["AUT",3],["CNF",3]],"B":[["AUT",-2],["CNS",3]],"C":[["AUT",2],["RIS",-1]],"D":[["AUT",-3],["RIS",-3]]}}'::jsonb, 71),
  ('ntc-assessment', 3, 'mcq:D12', '{"id":"D12","dim":"AUT","text":"Votre supérieur indisponible, décision urgente relevant normalement de lui. Vous :","o":{"A":"La prenez vous-même, en assumant.","B":"Trouvez un autre supérieur pour valider.","C":"Attendez son retour si le délai le permet.","D":"La prenez, en documentant votre raisonnement."},"w":{"A":[["AUT",3],["CNF",3]],"B":[["AUT",-2]],"C":[["AUT",-3],["RIS",-3]],"D":[["AUT",3]]}}'::jsonb, 72),
  ('ntc-assessment', 3, 'mcq:D13', '{"id":"D13","dim":"AUT","text":"Vous recevez un avis contraire au vôtre de quelqu''un que vous respectez beaucoup. Vous :","o":{"A":"Changez d''avis, cette personne a probablement raison.","B":"Maintenez votre position après l''avoir sérieusement pesée.","C":"Cherchez un troisième avis pour départager.","D":"Adoptez une position intermédiaire par prudence."},"w":{"A":[["AUT",-3],["CNF",-2]],"B":[["AUT",3],["CNF",3]],"C":[["AUT",-1],["CNS",2]],"D":[["AUT",-2]]}}'::jsonb, 73),
  ('ntc-assessment', 3, 'mcq:D14', '{"id":"D14","dim":"AUT","text":"Le groupe penche clairement vers une direction que vous jugez erronée. Vous :","o":{"A":"Exprimez votre désaccord clairement, même seul contre tous.","B":"Vous ralliez à la majorité.","C":"Exprimez une réserve nuancée sans insister.","D":"Gardez le silence."},"w":{"A":[["AUT",3],["CNF",3]],"B":[["AUT",-3],["CNS",3]],"C":[["AUT",2]],"D":[["AUT",-2],["CNF",-2]]}}'::jsonb, 74),
  ('ntc-assessment', 3, 'mcq:D15', '{"id":"D15","dim":"AUT","text":"Un modèle existe déjà, mais vous pensez pouvoir faire mieux différemment. Vous :","o":{"A":"Suivez le modèle existant.","B":"Développez votre propre méthode, quitte à devoir la justifier.","C":"Adaptez le modèle existant à la marge.","D":"Demandez d''abord l''avis de votre hiérarchie."},"w":{"A":[["AUT",-2]],"B":[["AUT",3],["RIS",2]],"C":[["AUT",2]],"D":[["AUT",-2],["CNS",1]]}}'::jsonb, 75),
  ('ntc-assessment', 3, 'mcq:D16', '{"id":"D16","dim":"CNS","text":"Faire adopter un changement de process par une équipe majoritairement réticente. Vous :","o":{"A":"Imposez le changement.","B":"Convainquez chacun individuellement avant de lancer.","C":"Organisez un atelier collectif pour co-construire.","D":"Lancez un test limité pour laisser les faits convaincre."},"w":{"A":[["CNS",-3],["LDD",3]],"B":[["CNS",3]],"C":[["CNS",3],["DEL",1]],"D":[["CNS",2]]}}'::jsonb, 76),
  ('ntc-assessment', 3, 'mcq:D17', '{"id":"D17","dim":"CNS","text":"Deux visions opposées coexistent dans l''équipe, chacune avec de bons arguments. Vous :","o":{"A":"Tranchez selon votre propre analyse.","B":"Cherchez une troisième voie intégrant les deux visions.","C":"Organisez un vote pour laisser le groupe trancher.","D":"Laissez la décision émerger naturellement."},"w":{"A":[["CNS",-3],["LDD",3]],"B":[["CNS",3]],"C":[["CNS",3]],"D":[["CNS",2],["LDD",-2]]}}'::jsonb, 77),
  ('ntc-assessment', 3, 'mcq:D18', '{"id":"D18","dim":"CNS","text":"Vous êtes convaincu d''avoir raison mais l''équipe n''est pas alignée, le délai ne presse pas. Vous :","o":{"A":"Décidez quand même.","B":"Investissez le temps nécessaire pour un vrai accord collectif.","C":"Cherchez un compromis satisfaisant la majorité.","D":"Laissez tomber l''idée si l''équipe n''y adhère pas."},"w":{"A":[["CNS",-3],["CNF",3]],"B":[["CNS",3]],"C":[["CNS",2]],"D":[["CNS",3],["LDD",-2]]}}'::jsonb, 78),
  ('ntc-assessment', 3, 'mcq:D19', '{"id":"D19","dim":"CNS","text":"Un collaborateur exprime seul un désaccord sur une décision déjà largement approuvée. Vous :","o":{"A":"Maintenez la décision, la majorité a tranché.","B":"Prenez le temps d''écouter et de comprendre son désaccord en profondeur.","C":"Lui expliquez les raisons sans revenir dessus.","D":"Rouvrez la discussion pour tout le groupe si l''argument semble solide."},"w":{"A":[["CNS",-2]],"B":[["CNS",2]],"C":[["CNS",-1]],"D":[["CNS",3]]}}'::jsonb, 79),
  ('ntc-assessment', 3, 'mcq:D20', '{"id":"D20","dim":"CNS","text":"Vous animez une réunion où le silence s''installe après votre proposition. Vous :","o":{"A":"Considérez que le silence vaut accord.","B":"Sollicitez explicitement chaque personne pour un avis individuel.","C":"Reformulez la proposition.","D":"Proposez de trancher seul puisque personne ne réagit."},"w":{"A":[["CNS",-2]],"B":[["CNS",3]],"C":[["CNS",2]],"D":[["CNS",-3],["LDD",3]]}}'::jsonb, 80),
  ('ntc-assessment', 3, 'mcq:D21', '{"id":"D21","dim":"RIS","text":"Gain modéré quasi certain, ou gain important avec 40 % d''échec total. Vous :","o":{"A":"Choisissez l''option sûre, systématiquement.","B":"Choisissez l''option ambitieuse.","C":"Cherchez à réduire le risque de l''option ambitieuse avant de choisir.","D":"Combinez les deux si possible."},"w":{"A":[["RIS",-3]],"B":[["RIS",3]],"C":[["RIS",2]],"D":[["RIS",2]]}}'::jsonb, 81),
  ('ntc-assessment', 3, 'mcq:D22', '{"id":"D22","dim":"RIS","text":"Un projet en lequel vous croyez fortement n''a pas encore de résultats prouvés ailleurs. Vous :","o":{"A":"Vous lancez sans attendre de preuve externe.","B":"Attendez qu''un cas similaire ait réussi ailleurs.","C":"Lancez une version réduite pour tester.","D":"Renoncez, le risque est trop élevé."},"w":{"A":[["RIS",3],["CNF",3]],"B":[["RIS",-3]],"C":[["RIS",2]],"D":[["RIS",-3]]}}'::jsonb, 82),
  ('ntc-assessment', 3, 'mcq:D23', '{"id":"D23","dim":"RIS","text":"Une opportunité rentable implique de miser une part importante des ressources sur un seul choix. Vous :","o":{"A":"Saisissez l''opportunité pleinement.","B":"La saisissez partiellement, en gardant une réserve.","C":"La laissez passer, la concentration du risque est trop élevée.","D":"Cherchez d''abord un partenaire pour partager le risque."},"w":{"A":[["RIS",3]],"B":[["RIS",2]],"C":[["RIS",-3]],"D":[["RIS",2]]}}'::jsonb, 83),
  ('ntc-assessment', 3, 'mcq:D24', '{"id":"D24","dim":"RIS","text":"Méthode éprouvée mais lente, ou méthode nouvelle jamais testée mais potentiellement plus rapide. Vous :","o":{"A":"Restez sur la méthode éprouvée.","B":"Adoptez pleinement la nouvelle méthode.","C":"Testez sur un périmètre limité d''abord.","D":"Alternez selon le contexte."},"w":{"A":[["RIS",-3]],"B":[["RIS",3]],"C":[["RIS",2]],"D":[["RIS",2]]}}'::jsonb, 84),
  ('ntc-assessment', 3, 'mcq:D25', '{"id":"D25","dim":"RIS","text":"Après un échec récent lié à une décision risquée, une situation similaire se représente. Vous :","o":{"A":"Reprenez le même type de risque.","B":"Devenez nettement plus prudent.","C":"Analysez précisément ce qui a échoué avant d''agir.","D":"Évitez complètement ce type de situation à l''avenir."},"w":{"A":[["RIS",3],["CNF",3]],"B":[["RIS",-2]],"C":[["RIS",2]],"D":[["RIS",-3]]}}'::jsonb, 85),
  ('ntc-assessment', 3, 'mcq:D26', '{"id":"D26","dim":"CNF","text":"Une décision prise seul est publiquement remise en question par quelqu''un d''expérience. Vous :","o":{"A":"Défendez votre décision avec les arguments qui l''ont motivée.","B":"Doutez immédiatement et reconsidérez.","C":"Défendez en public, reconsidérez sérieusement en privé.","D":"Changez de position pour éviter le conflit."},"w":{"A":[["CNF",3]],"B":[["CNF",-3]],"C":[["CNF",3]],"D":[["CNF",-3]]}}'::jsonb, 86),
  ('ntc-assessment', 3, 'mcq:D27', '{"id":"D27","dim":"CNF","text":"Choisir entre votre intuition et une analyse plus poussée pointant dans une direction légèrement différente. Vous :","o":{"A":"Suivez votre intuition.","B":"Suivez systématiquement l''analyse.","C":"Cherchez à comprendre l''écart avant de choisir.","D":"Suivez l''analyse cette fois, par prudence."},"w":{"A":[["CNF",3]],"B":[["CNF",-2]],"C":[["CNF",2]],"D":[["CNF",-1]]}}'::jsonb, 87),
  ('ntc-assessment', 3, 'mcq:D28', '{"id":"D28","dim":"CNF","text":"Après plusieurs décisions réussies d''affilée, une nouvelle décision importante se présente. Vous :","o":{"A":"Abordez avec la même assurance que les précédentes.","B":"Redoublez de prudence, le succès peut cacher un excès de confiance.","C":"Demandez un avis extérieur par précaution systématique.","D":"Ne changez rien à votre approche habituelle."},"w":{"A":[["CNF",3]],"B":[["CNF",2]],"C":[["CNF",-1],["CNS",1]],"D":[["CNF",3]]}}'::jsonb, 88),
  ('ntc-assessment', 3, 'mcq:D29', '{"id":"D29","dim":"CNF","text":"Une décision s''avère, après coup, clairement mauvaise. Vous :","o":{"A":"Assumez pleinement, en analysant ce qui a manqué.","B":"Doutez fortement de votre jugement pour l''avenir.","C":"Cherchez des circonstances atténuantes externes.","D":"Passez rapidement à autre chose sans y revenir."},"w":{"A":[["CNF",3]],"B":[["CNF",-3]],"C":[["CNF",2],["INT",-1]],"D":[["CNF",2]]}}'::jsonb, 89),
  ('ntc-assessment', 3, 'mcq:D30', '{"id":"D30","dim":"CNF","text":"On vous demande de trancher rapidement sans toutes les données idéales. Vous :","o":{"A":"Tranchez avec ce que vous avez.","B":"Refusez de trancher tant que l''information n''est pas complète.","C":"Tranchez, en signalant explicitement l''incertitude.","D":"Demandez à quelqu''un d''autre de trancher, faute de données."},"w":{"A":[["CNF",3],["RIS",2]],"B":[["CNF",-2],["RIS",-3]],"C":[["CNF",3]],"D":[["CNF",-3],["DEL",3]]}}'::jsonb, 90),
  ('ntc-assessment', 4, 'mcq:L1', '{"id":"L1","dim":"DIR","text":"Un nouveau membre, peu autonome, doit accomplir une tâche inhabituelle pour la première fois. Vous :","o":{"A":"Lui donnez des instructions précises, étape par étape.","B":"Lui expliquez l''objectif et le laissez trouver sa méthode.","C":"Travaillez la tâche avec lui, à ses côtés.","D":"Le mettez en binôme avec quelqu''un d''expérimenté."},"w":{"A":[["DIR",3]],"B":[["PAR",2],["SER",1]],"C":[["SER",3]],"D":[["PAR",2],["SER",2]]}}'::jsonb, 91),
  ('ntc-assessment', 4, 'mcq:L2', '{"id":"L2","dim":"DIR","text":"Urgence opérationnelle, pas de temps pour discuter des options. Vous :","o":{"A":"Donnez des instructions claires et attendez l''exécution immédiate.","B":"Rassemblez rapidement les avis avant de trancher.","C":"Rappelez l''objectif final et laissez chacun s''organiser.","D":"Prenez les devants vous-même, en montrant l''exemple."},"w":{"A":[["DIR",3]],"B":[["PAR",3]],"C":[["TRA",2]],"D":[["CHA",2],["DIR",1]]}}'::jsonb, 92),
  ('ntc-assessment', 4, 'mcq:L3', '{"id":"L3","dim":"DIR","text":"Un résultat n''est pas conforme à ce qui était demandé. Vous :","o":{"A":"Précisez à nouveau, très clairement, ce qui était attendu.","B":"Demandez ce qui a causé l''écart, avant de recadrer.","C":"Réexpliquez le sens de la tâche plutôt que ses modalités.","D":"Refaites la tâche vous-même."},"w":{"A":[["DIR",3]],"B":[["PAR",2],["SER",1]],"C":[["TRA",2]],"D":[["DIR",1]]}}'::jsonb, 93),
  ('ntc-assessment', 4, 'mcq:L4', '{"id":"L4","dim":"DIR","text":"Encadrer une équipe peu expérimentée sur un sujet à fort enjeu de conformité. Vous :","o":{"A":"Fixez des règles précises et vérifiez leur application de près.","B":"Expliquez le pourquoi et faites confiance à l''application.","C":"Impliquez l''équipe dans la définition des points de contrôle.","D":"Formez un référent qualité au sein de l''équipe."},"w":{"A":[["DIR",3]],"B":[["TRA",2]],"C":[["PAR",3]],"D":[["SER",2],["STR",1]]}}'::jsonb, 94),
  ('ntc-assessment', 4, 'mcq:L5', '{"id":"L5","dim":"DIR","text":"Un collaborateur demande simplement « que dois-je faire ? » sans autre précision. Vous :","o":{"A":"Lui donnez une réponse claire et actionnable immédiatement.","B":"Lui retournez la question pour qu''il structure sa propre réponse.","C":"Explorez avec lui ce qui bloque sa capacité à trancher seul.","D":"Lui rappelez la vision d''ensemble."},"w":{"A":[["DIR",3]],"B":[["PAR",2],["SER",1]],"C":[["SER",3]],"D":[["TRA",2]]}}'::jsonb, 95),
  ('ntc-assessment', 4, 'mcq:L6', '{"id":"L6","dim":"PAR","text":"Vous devez définir les objectifs de l''équipe pour le trimestre à venir. Vous :","o":{"A":"Les fixez vous-même selon votre analyse.","B":"Organisez un atelier collectif pour les co-construire.","C":"Présentez une vision inspirante des enjeux.","D":"Demandez à chacun ses objectifs individuels et les assemblez."},"w":{"A":[["DIR",3],["STR",2]],"B":[["PAR",3]],"C":[["TRA",3]],"D":[["PAR",2]]}}'::jsonb, 96),
  ('ntc-assessment', 4, 'mcq:L7', '{"id":"L7","dim":"PAR","text":"Une décision impacte le quotidien de l''équipe, mais vous avez déjà une intuition claire. Vous :","o":{"A":"Décidez selon votre intuition.","B":"Consultez l''équipe malgré tout.","C":"Partagez votre intuition et ouvrez la discussion.","D":"Laissez l''équipe décider entièrement."},"w":{"A":[["DIR",3]],"B":[["PAR",3]],"C":[["PAR",2],["TRA",1]],"D":[["SER",3],["PAR",1]]}}'::jsonb, 97),
  ('ntc-assessment', 4, 'mcq:L8', '{"id":"L8","dim":"PAR","text":"Un sujet sensible divise l''équipe, chacun campe sur sa position. Vous :","o":{"A":"Tranchez vous-même pour mettre fin au blocage.","B":"Organisez un espace structuré où chacun expose ses arguments.","C":"Rappelez l''objectif commun pour recentrer le débat.","D":"Prenez chacun individuellement avant de revenir vers le groupe."},"w":{"A":[["DIR",3]],"B":[["PAR",3]],"C":[["TRA",2]],"D":[["SER",2],["PAR",1]]}}'::jsonb, 98),
  ('ntc-assessment', 4, 'mcq:L9', '{"id":"L9","dim":"PAR","text":"L''équipe a des idées pour améliorer un process mais ne les partage jamais spontanément. Vous :","o":{"A":"Mettez en place un rituel régulier de recueil d''idées.","B":"Décidez que ce n''est pas la priorité.","C":"Allez chercher individuellement les idées de chacun.","D":"Communiquez une vision claire pour orienter les idées."},"w":{"A":[["PAR",3]],"B":[["DIR",2]],"C":[["SER",2],["PAR",1]],"D":[["TRA",2]]}}'::jsonb, 99),
  ('ntc-assessment', 4, 'mcq:L10', '{"id":"L10","dim":"PAR","text":"Choisir un nouvel outil de travail, plusieurs options techniques existent. Vous :","o":{"A":"Choisissez celui qui vous semble techniquement le meilleur.","B":"Faites tester plusieurs options par l''équipe avant de décider ensemble.","C":"Confiez le choix à la personne la plus compétente.","D":"Choisissez celui qui incarne le mieux la direction future."},"w":{"A":[["DIR",2],["STR",1]],"B":[["PAR",3]],"C":[["SER",1]],"D":[["STR",3],["TRA",1]]}}'::jsonb, 100),
  ('ntc-assessment', 4, 'mcq:L11', '{"id":"L11","dim":"TRA","text":"L''équipe traverse une période difficile et la motivation baisse. Vous :","o":{"A":"Fixez des objectifs plus précis et un suivi plus serré.","B":"Rappelez pourquoi le travail de l''équipe compte, au-delà des chiffres.","C":"Prenez le temps individuellement d''écouter chacun.","D":"Analysez les causes structurelles de la baisse."},"w":{"A":[["DIR",3]],"B":[["TRA",3]],"C":[["SER",3]],"D":[["STR",2]]}}'::jsonb, 101),
  ('ntc-assessment', 4, 'mcq:L12', '{"id":"L12","dim":"TRA","text":"Vous voulez qu''une équipe dépasse ses standards habituels sur un projet clé. Vous :","o":{"A":"Fixez des objectifs chiffrés ambitieux et suivez de près.","B":"Partagez une vision de ce que ce projet représente.","C":"Impliquez l''équipe dans la définition du niveau d''ambition.","D":"Vous appuyez sur votre propre énergie pour entraîner le groupe."},"w":{"A":[["DIR",3]],"B":[["TRA",3]],"C":[["PAR",2]],"D":[["CHA",3]]}}'::jsonb, 102),
  ('ntc-assessment', 4, 'mcq:L13', '{"id":"L13","dim":"TRA","text":"Un projet long terme demande des efforts soutenus sans résultats visibles à court terme. Vous :","o":{"A":"Détaillez un plan d''étapes précises pour maintenir le cap.","B":"Reconnectez régulièrement l''équipe au sens et à l''impact final.","C":"Vous assurez que chacun dispose des ressources nécessaires.","D":"Ajustez la stratégie régulièrement selon les signaux du terrain."},"w":{"A":[["DIR",2]],"B":[["TRA",3]],"C":[["SER",3]],"D":[["STR",3]]}}'::jsonb, 103),
  ('ntc-assessment', 4, 'mcq:L14', '{"id":"L14","dim":"TRA","text":"Vous intégrez une nouvelle recrue dans l''équipe. Vous :","o":{"A":"Lui donnez un plan d''intégration détaillé avec jalons précis.","B":"Lui partagez la mission et les valeurs en priorité.","C":"Prenez le temps de comprendre ses attentes personnelles.","D":"La mettez rapidement en situation réelle."},"w":{"A":[["DIR",3]],"B":[["TRA",3]],"C":[["SER",3]],"D":[["STR",1],["DIR",1]]}}'::jsonb, 104),
  ('ntc-assessment', 4, 'mcq:L15', '{"id":"L15","dim":"TRA","text":"Un collaborateur talentueux semble sous-performer par manque d''ambition perçue. Vous :","o":{"A":"Fixez des objectifs plus élevés et un suivi renforcé.","B":"Lui montrez une trajectoire qui donne un sens plus grand.","C":"Discutez avec lui de ce qui freine réellement sa motivation.","D":"Lui confiez un projet stratégique à plus fort enjeu."},"w":{"A":[["DIR",2]],"B":[["TRA",3]],"C":[["SER",3]],"D":[["STR",2],["TRA",1]]}}'::jsonb, 105),
  ('ntc-assessment', 4, 'mcq:L16', '{"id":"L16","dim":"SER","text":"Un membre de l''équipe traverse une période personnelle difficile qui affecte son travail. Vous :","o":{"A":"Maintenez les exigences habituelles.","B":"Ajustez temporairement sa charge et ses délais.","C":"Lui rappelez la vision d''équipe pour l''aider à se remobiliser.","D":"Le mettez en retrait temporaire des dossiers sensibles."},"w":{"A":[["DIR",2]],"B":[["SER",3]],"C":[["TRA",2]],"D":[["STR",1],["SER",1]]}}'::jsonb, 106),
  ('ntc-assessment', 4, 'mcq:L17', '{"id":"L17","dim":"SER","text":"Répartir les tâches valorisantes et ingrates au sein de l''équipe. Vous :","o":{"A":"Prenez pour vous-même une part des tâches ingrates.","B":"Répartissez selon les compétences, sans considération d''équité de valorisation.","C":"Alternez pour que chacun ait sa part des deux.","D":"Confiez les tâches valorisantes aux plus performants."},"w":{"A":[["SER",3]],"B":[["DIR",2],["STR",1]],"C":[["PAR",1],["SER",2]],"D":[["STR",2]]}}'::jsonb, 107),
  ('ntc-assessment', 4, 'mcq:L18', '{"id":"L18","dim":"SER","text":"Un collaborateur réussit grâce à votre accompagnement rapproché. À la reconnaissance publique, vous :","o":{"A":"Mettez en avant son mérite personnel, sans mentionner votre rôle.","B":"Partagez équitablement le crédit entre vous deux.","C":"Mettez en avant votre propre rôle de coach.","D":"Soulignez la réussite collective de toute l''équipe."},"w":{"A":[["SER",3]],"B":[["PAR",1]],"C":[["CHA",1],["SER",-2]],"D":[["TRA",2]]}}'::jsonb, 108),
  ('ntc-assessment', 4, 'mcq:L19', '{"id":"L19","dim":"SER","text":"Un collaborateur pourrait, à terme, dépasser votre propre niveau de compétence sur un sujet clé. Vous :","o":{"A":"L''encouragez activement à développer cette compétence.","B":"Restez le référent principal sur le sujet, par prudence.","C":"Partagez le sujet en binôme pour garder un pied dedans.","D":"Le mettez en avant publiquement dès que pertinent."},"w":{"A":[["SER",3]],"B":[["DIR",1]],"C":[["PAR",1]],"D":[["SER",2],["TRA",1]]}}'::jsonb, 109),
  ('ntc-assessment', 4, 'mcq:L20', '{"id":"L20","dim":"STR","text":"Allouer un budget limité entre plusieurs initiatives, toutes légitimes. Vous :","o":{"A":"Répartissez équitablement entre toutes.","B":"Concentrez le budget sur l''initiative alignée avec la direction à 3 ans.","C":"Laissez l''équipe décider collectivement.","D":"Financez en priorité ce qui produit un résultat visible rapidement."},"w":{"A":[["PAR",1]],"B":[["STR",3]],"C":[["PAR",3]],"D":[["DIR",1],["STR",-1]]}}'::jsonb, 110),
  ('ntc-assessment', 4, 'mcq:L21', '{"id":"L21","dim":"STR","text":"Une opportunité immédiate rentable détournerait des ressources d''un projet structurant à plus long terme. Vous :","o":{"A":"Saisissez l''opportunité, un gain concret compte plus.","B":"Refusez, le projet structurant reste la priorité.","C":"Évaluez précisément l''impact sur la trajectoire à 3 ans.","D":"Cherchez un moyen de faire les deux en parallèle."},"w":{"A":[["DIR",1],["STR",-2]],"B":[["STR",3]],"C":[["STR",3]],"D":[["STR",2]]}}'::jsonb, 111),
  ('ntc-assessment', 4, 'mcq:L22', '{"id":"L22","dim":"STR","text":"Présenter la direction à 3 ans de votre équipe à la direction générale. Vous :","o":{"A":"Présentez un plan détaillé d''exécution, étape par étape.","B":"Présentez une vision large, connectée aux enjeux globaux.","C":"Présentez ce que l''équipe a co-construit comme trajectoire.","D":"Présentez avec conviction et énergie pour emporter l''adhésion."},"w":{"A":[["DIR",2]],"B":[["STR",3]],"C":[["PAR",3]],"D":[["CHA",3]]}}'::jsonb, 112),
  ('ntc-assessment', 4, 'mcq:L23', '{"id":"L23","dim":"STR","text":"Deux talents en concurrence implicite pour un même poste à pourvoir dans 12 mois. Vous :","o":{"A":"Laissez la compétition se jouer naturellement sur les résultats.","B":"Développez les deux différemment, selon une vision des besoins futurs.","C":"En discutez ouvertement avec les deux.","D":"Choisissez dès maintenant pour éviter toute tension."},"w":{"A":[["DIR",1]],"B":[["STR",3]],"C":[["PAR",2],["SER",1]],"D":[["DIR",2],["STR",-1]]}}'::jsonb, 113),
  ('ntc-assessment', 4, 'mcq:L24', '{"id":"L24","dim":"STR","text":"Un concurrent lance une offre qui pourrait rendre une partie de votre activité obsolète. Vous :","o":{"A":"Réagissez rapidement pour contrer l''offre sur le même terrain.","B":"Prenez le temps d''évaluer la trajectoire à 3-5 ans avant de repositionner.","C":"Consultez l''équipe pour construire collectivement la réponse.","D":"Mobilisez l''équipe autour d''une nouvelle ambition."},"w":{"A":[["DIR",1],["STR",-1]],"B":[["STR",3]],"C":[["PAR",2]],"D":[["TRA",3]]}}'::jsonb, 114),
  ('ntc-assessment', 4, 'mcq:L25', '{"id":"L25","dim":"CHA","text":"Mobiliser une équipe fatiguée pour un dernier effort avant une échéance importante. Vous :","o":{"A":"Détaillez précisément ce qui reste à faire et le planning.","B":"Prenez la parole avec une énergie visible pour redonner de l''élan.","C":"Prenez soin individuellement de chacun.","D":"Rappelez la vision et l''impact final du projet."},"w":{"A":[["DIR",2]],"B":[["CHA",3]],"C":[["SER",3]],"D":[["TRA",3]]}}'::jsonb, 115),
  ('ntc-assessment', 4, 'mcq:L26', '{"id":"L26","dim":"CHA","text":"Négociation difficile, la salle a besoin d''être rassurée sur la solidité du projet. Vous :","o":{"A":"Présentez des chiffres et des faits précis, méthodiquement.","B":"Prenez la parole avec assurance pour incarner la confiance dans le projet.","C":"Laissez chacun de l''équipe présenter sa partie.","D":"Rappelez la vision de long terme du partenariat."},"w":{"A":[["STR",1],["DIR",1]],"B":[["CHA",3]],"C":[["PAR",2]],"D":[["TRA",2],["STR",1]]}}'::jsonb, 116),
  ('ntc-assessment', 4, 'mcq:L27', '{"id":"L27","dim":"CHA","text":"Vous remarquez que votre seule présence change la dynamique et l''engagement du groupe. Vous :","o":{"A":"En êtes mal à l''aise, préféreriez que le groupe fonctionne sans vous.","B":"L''utilisez consciemment pour porter les moments clés, tout en développant l''autonomie du groupe.","C":"L''utilisez systématiquement pour orienter toutes les décisions.","D":"N''y prêtez pas particulièrement attention."},"w":{"A":[["SER",1],["CHA",-1]],"B":[["CHA",3]],"C":[["CHA",3],["DIR",1]],"D":[["CHA",-2]]}}'::jsonb, 117),
  ('ntc-assessment', 4, 'mcq:L28', '{"id":"L28","dim":"CHA","text":"Annoncer une bonne nouvelle importante à toute l''organisation. Vous :","o":{"A":"Envoyez une communication écrite claire et factuelle.","B":"Prenez la parole en personne, avec une énergie qui marque les esprits.","C":"Laissez chaque manager l''annoncer à sa façon.","D":"Reconnectez tout le monde à la vision d''ensemble."},"w":{"A":[["DIR",1],["STR",1]],"B":[["CHA",3]],"C":[["PAR",2]],"D":[["TRA",3]]}}'::jsonb, 118),
  ('ntc-assessment', 5, 'mcq:S1', '{"id":"S1","dim":"EMP","text":"Un collaborateur annonce, voix hésitante, ne pas avoir atteint ses objectifs. Votre première réaction :","o":{"A":"Lui demander directement les chiffres précis.","B":"Remarquer son hésitation et demander comment il vit la situation.","C":"Le rassurer immédiatement en minimisant l''écart.","D":"Lui proposer un plan d''action correctif sans attendre."},"w":{"A":[["EMP",-2]],"B":[["EMP",3],["ECO",3]],"C":[["EMP",2]],"D":[["EMP",-1]]}}'::jsonb, 119),
  ('ntc-assessment', 5, 'mcq:S2', '{"id":"S2","dim":"EMP","text":"Un membre de l''équipe reste silencieux en réunion, alors qu''il est habituellement actif. Vous :","o":{"A":"Continuez la réunion normalement.","B":"Le sollicitez directement pour connaître son avis.","C":"Remarquez le changement et vérifiez après coup que tout va bien.","D":"Interprétez son silence comme un accord tacite."},"w":{"A":[["EMP",-2]],"B":[["ECO",2],["EMP",1]],"C":[["EMP",3]],"D":[["EMP",-3]]}}'::jsonb, 120),
  ('ntc-assessment', 5, 'mcq:S3', '{"id":"S3","dim":"EMP","text":"Un client se plaint avec une émotion disproportionnée par rapport au problème technique réel. Vous :","o":{"A":"Corrigez rapidement le problème technique.","B":"Reconnaissez d''abord la frustration exprimée.","C":"Faites remarquer poliment que la réaction semble excessive.","D":"Transférez l''appel à un collègue."},"w":{"A":[["EMP",-1]],"B":[["EMP",3]],"C":[["EMP",-3]],"D":[["EMP",1]]}}'::jsonb, 121),
  ('ntc-assessment', 5, 'mcq:S4', '{"id":"S4","dim":"EMP","text":"Un collaborateur performant demande soudainement un aménagement d''horaires sans raison précise. Vous :","o":{"A":"Traitez la demande selon la procédure standard.","B":"Lui demandez ouvertement ce qui motive ce changement.","C":"Accordez l''aménagement sans poser de questions.","D":"Refusez temporairement, le temps de comprendre."},"w":{"A":[["EMP",-2]],"B":[["EMP",3],["ECO",2]],"C":[["EMP",2]],"D":[["EMP",-2]]}}'::jsonb, 122),
  ('ntc-assessment', 5, 'mcq:S5', '{"id":"S5","dim":"EMP","text":"En entretien annuel, un collaborateur évoque brièvement une difficulté personnelle puis change de sujet. Vous :","o":{"A":"Respectez son choix.","B":"Revenez doucement sur le sujet plus tard, sans insister.","C":"Insistez immédiatement pour comprendre.","D":"Notez l''information pour le suivi futur, sans rien dire sur le moment."},"w":{"A":[["EMP",2]],"B":[["EMP",3]],"C":[["EMP",-1]],"D":[["EMP",2]]}}'::jsonb, 123),
  ('ntc-assessment', 5, 'mcq:S6', '{"id":"S6","dim":"EMP","text":"Annoncer une mauvaise nouvelle à quelqu''un déjà fragilisé par ailleurs. Vous :","o":{"A":"L''annoncez directement, la clarté prime.","B":"Adaptez votre approche et timing à son état, sans changer le fond.","C":"Retardez l''annonce en espérant que ça se tasse.","D":"Demandez à quelqu''un d''autre de l''annoncer."},"w":{"A":[["EMP",-2]],"B":[["EMP",3],["DIP",2]],"C":[["EMP",-1]],"D":[["EMP",1]]}}'::jsonb, 124),
  ('ntc-assessment', 5, 'mcq:S7', '{"id":"S7","dim":"ECO","text":"Pendant qu''un collaborateur expose un problème, vous pensez déjà avoir compris la solution. Vous :","o":{"A":"L''interrompez pour proposer la solution.","B":"Le laissez terminer avant de proposer quoi que ce soit.","C":"Attendez une pause naturelle pour vérifier votre compréhension.","D":"Prenez des notes sans intervenir jusqu''à la fin."},"w":{"A":[["ECO",-3]],"B":[["ECO",3]],"C":[["ECO",3]],"D":[["ECO",2]]}}'::jsonb, 125),
  ('ntc-assessment', 5, 'mcq:S8', '{"id":"S8","dim":"ECO","text":"Un collaborateur répète un point que vous pensez avoir déjà bien compris. Vous :","o":{"A":"Le lui signalez pour ne pas perdre de temps.","B":"Le laissez terminer, une nuance vous a peut-être échappé.","C":"Changez de sujet discrètement.","D":"Reformulez ce que vous avez compris pour vérifier l''alignement."},"w":{"A":[["ECO",-2]],"B":[["ECO",3]],"C":[["ECO",-3]],"D":[["ECO",3]]}}'::jsonb, 126),
  ('ntc-assessment', 5, 'mcq:S9', '{"id":"S9","dim":"ECO","text":"Dans une discussion à plusieurs, deux personnes parlent en même temps. Vous :","o":{"A":"Répondez à celle qui a la position hiérarchique la plus élevée.","B":"Demandez à chacune de s''exprimer à tour de rôle.","C":"Répondez à celle qui a parlé le plus fort ou en premier.","D":"Attendez que le silence se fasse naturellement."},"w":{"A":[["ECO",-2]],"B":[["ECO",3]],"C":[["ECO",-3]],"D":[["ECO",2]]}}'::jsonb, 127),
  ('ntc-assessment', 5, 'mcq:S10', '{"id":"S10","dim":"ECO","text":"Un collaborateur donne un avis que vous jugez immédiatement peu pertinent. Vous :","o":{"A":"Le lui dites franchement pour ne pas perdre de temps.","B":"Creusez son raisonnement avant de juger.","C":"Hochez la tête poliment sans approfondir.","D":"Changez rapidement de sujet."},"w":{"A":[["ECO",-2]],"B":[["ECO",3]],"C":[["ECO",-2]],"D":[["ECO",-3]]}}'::jsonb, 128),
  ('ntc-assessment', 5, 'mcq:S11', '{"id":"S11","dim":"ECO","text":"Vous recevez un feedback critique sur votre propre façon de manager. Vous :","o":{"A":"L''écoutez entièrement avant de réagir, même en désaccord sur le fond.","B":"Répondez immédiatement point par point.","C":"Remerciez poliment sans vraiment intégrer le contenu.","D":"Demandez des exemples concrets avant de répondre."},"w":{"A":[["ECO",3]],"B":[["ECO",-2]],"C":[["ECO",-3]],"D":[["ECO",3]]}}'::jsonb, 129),
  ('ntc-assessment', 5, 'mcq:S12', '{"id":"S12","dim":"DIP","text":"Signaler à un collègue d''un autre département une erreur qui affecte votre travail. Vous :","o":{"A":"La signalez directement et factuellement.","B":"Trouvez le bon moment et la bonne formulation.","C":"Passez par son manager plutôt que directement.","D":"Laissez tomber."},"w":{"A":[["DIP",-2]],"B":[["DIP",3]],"C":[["DIP",-1]],"D":[["DIP",1]]}}'::jsonb, 130),
  ('ntc-assessment', 5, 'mcq:S13', '{"id":"S13","dim":"DIP","text":"Refuser une demande d''un partenaire important sans compromettre la relation long terme. Vous :","o":{"A":"Refusez clairement et directement.","B":"Refusez en expliquant le contexte et en proposant une alternative.","C":"Repoussez la réponse pour éviter le refus direct.","D":"Acceptez partiellement pour ne pas fâcher."},"w":{"A":[["DIP",-2],["INT",2]],"B":[["DIP",3]],"C":[["DIP",-1]],"D":[["DIP",1]]}}'::jsonb, 131),
  ('ntc-assessment', 5, 'mcq:S14', '{"id":"S14","dim":"DIP","text":"Un senior donne, en public, un avis que vous jugez erroné sur un sujet que vous maîtrisez mieux. Vous :","o":{"A":"Le corrigez directement, devant tout le monde.","B":"Apportez une nuance respectueuse sur le moment.","C":"Ne dites rien en public, corrigez en privé ensuite.","D":"Laissez passer."},"w":{"A":[["DIP",-3]],"B":[["DIP",3],["COU",2]],"C":[["DIP",3]],"D":[["DIP",1]]}}'::jsonb, 132),
  ('ntc-assessment', 5, 'mcq:S15', '{"id":"S15","dim":"DIP","text":"Transmettre à l''équipe une décision de direction impopulaire et mal expliquée. Vous :","o":{"A":"La transmettez telle quelle.","B":"Prenez le temps de la recontextualiser pour qu''elle soit mieux comprise.","C":"Exprimez votre propre désaccord en même temps.","D":"Retardez la transmission en espérant qu''elle soit reconsidérée."},"w":{"A":[["DIP",2]],"B":[["DIP",3]],"C":[["DIP",-2]],"D":[["DIP",-1]]}}'::jsonb, 133),
  ('ntc-assessment', 5, 'mcq:S16', '{"id":"S16","dim":"DIP","text":"Deux clients importants demandent, au même moment, un traitement prioritaire incompatible. Vous :","o":{"A":"Priorisez selon un critère objectif et l''assumez auprès des deux.","B":"Trouvez une formulation qui ménage les deux.","C":"Priorisez celui qui insiste le plus.","D":"Repoussez la décision."},"w":{"A":[["DIP",2]],"B":[["DIP",3]],"C":[["DIP",-2]],"D":[["DIP",-1]]}}'::jsonb, 134),
  ('ntc-assessment', 5, 'mcq:S17', '{"id":"S17","dim":"NEG","text":"Un partenaire propose des conditions en-dessous de ce que vous jugez juste, mais reste stratégique. Vous :","o":{"A":"Acceptez pour préserver la relation long terme.","B":"Contre-proposez fermement en argumentant votre valeur.","C":"Refusez catégoriquement sans contre-proposition.","D":"Cherchez un compromis qui débloque la situation."},"w":{"A":[["NEG",-2]],"B":[["NEG",3]],"C":[["NEG",-3]],"D":[["NEG",2]]}}'::jsonb, 135),
  ('ntc-assessment', 5, 'mcq:S18', '{"id":"S18","dim":"NEG","text":"Votre interlocuteur campe sur une position depuis le début sans bouger. Vous :","o":{"A":"Maintenez votre propre position tout aussi fermement.","B":"Cherchez à comprendre l''intérêt réel derrière sa position.","C":"Faites une concession pour débloquer.","D":"Mettez fin à la négociation."},"w":{"A":[["NEG",-2]],"B":[["NEG",3]],"C":[["NEG",2]],"D":[["NEG",-3]]}}'::jsonb, 136),
  ('ntc-assessment', 5, 'mcq:S19', '{"id":"S19","dim":"NEG","text":"Vous obtenez plus qu''espéré grâce à une erreur manifeste de l''autre partie. Vous :","o":{"A":"Profitez de l''accord tel qu''il est.","B":"Signalez l''erreur avant de finaliser.","C":"Profitez, mais restez prêt à ajuster si l''erreur est découverte.","D":"Renégociez vous-même un accord plus équilibré."},"w":{"A":[["NEG",3],["INT",-2]],"B":[["NEG",-2],["INT",3]],"C":[["NEG",2],["INT",-1]],"D":[["NEG",2],["INT",3]]}}'::jsonb, 137),
  ('ntc-assessment', 5, 'mcq:S20', '{"id":"S20","dim":"NEG","text":"Une négociation interne s''éternise sur un point mineur alors que l''essentiel est déjà acquis. Vous :","o":{"A":"Insistez jusqu''à obtenir gain de cause même sur ce point.","B":"Lâchez le point mineur pour sécuriser rapidement l''essentiel.","C":"Proposez d''échanger ce point contre une concession équivalente.","D":"Suspendez la négociation pour y revenir à tête reposée."},"w":{"A":[["NEG",-2]],"B":[["NEG",3]],"C":[["NEG",3]],"D":[["NEG",2]]}}'::jsonb, 138),
  ('ntc-assessment', 5, 'mcq:S21', '{"id":"S21","dim":"NEG","text":"Vous négociez avec quelqu''un ayant clairement moins de pouvoir de négociation. Vous :","o":{"A":"Utilisez pleinement votre position favorable.","B":"Modérez volontairement vos demandes pour un accord équilibré.","C":"Laissez l''autre partie proposer en premier.","D":"Proposez d''emblée des conditions déjà équilibrées."},"w":{"A":[["NEG",3]],"B":[["NEG",2]],"C":[["NEG",2]],"D":[["NEG",-2]]}}'::jsonb, 139),
  ('ntc-assessment', 5, 'mcq:S22', '{"id":"S22","dim":"INF","text":"Faire adopter une idée à un groupe sans pouvoir de décision formel pour l''imposer. Vous :","o":{"A":"Présentez des données solides et laissez les faits convaincre.","B":"Construisez des alliances individuelles avant la réunion collective.","C":"Faites appel à l''émotion et à la vision.","D":"Attendez qu''un décideur formel porte l''idée."},"w":{"A":[["INF",2]],"B":[["INF",3]],"C":[["INF",3]],"D":[["INF",-3]]}}'::jsonb, 140),
  ('ntc-assessment', 5, 'mcq:S23', '{"id":"S23","dim":"INF","text":"Une personne clé, sans autorité formelle, oriente systématiquement les décisions du groupe. Vous :","o":{"A":"Le neutralisez, ce type d''influence est un risque.","B":"L''observez et vous en inspirez pour développer votre propre influence.","C":"Passez par cette personne pour faire avancer vos idées.","D":"L''ignorez, seule l''autorité formelle compte."},"w":{"A":[["INF",-2]],"B":[["INF",3]],"C":[["INF",2],["PRA",1]],"D":[["INF",-3]]}}'::jsonb, 141),
  ('ntc-assessment', 5, 'mcq:S24', '{"id":"S24","dim":"INF","text":"Faire adhérer votre équipe à un changement impopulaire mais nécessaire. Vous :","o":{"A":"Imposez le changement en vous appuyant sur votre position hiérarchique.","B":"Identifiez les personnes les plus respectées et les convainquez en premier.","C":"Expliquez rationnellement, une fois, à tout le groupe.","D":"Laissez le changement s''imposer par lui-même."},"w":{"A":[["INF",-2]],"B":[["INF",3],["STR",1]],"C":[["INF",2]],"D":[["INF",-3]]}}'::jsonb, 142),
  ('ntc-assessment', 5, 'mcq:S25', '{"id":"S25","dim":"INF","text":"Votre proposition ne convainc pas malgré des arguments solides. Vous :","o":{"A":"Répétez les mêmes arguments plus fermement.","B":"Changez d''angle et reliez la proposition à ce qui compte pour l''audience.","C":"Laissez tomber la proposition pour cette fois.","D":"Demandez à quelqu''un de mieux perçu de porter l''idée."},"w":{"A":[["INF",-2]],"B":[["INF",3]],"C":[["INF",-3]],"D":[["INF",2]]}}'::jsonb, 143),
  ('ntc-assessment', 5, 'mcq:S26', '{"id":"S26","dim":"INF","text":"On vous demande d''appuyer publiquement une idée à laquelle vous ne croyez pas. Vous :","o":{"A":"L''appuyez, l''entraide entre collègues compte.","B":"Refusez d''utiliser votre influence pour une idée à laquelle vous ne croyez pas.","C":"Restez neutre publiquement.","D":"Exprimez vos réserves ouvertement."},"w":{"A":[["INF",-1],["INT",-2]],"B":[["INF",-1],["INT",3]],"C":[["INF",-1]],"D":[["INF",2],["INT",3]]}}'::jsonb, 144),
  ('ntc-assessment', 5, 'mcq:S27', '{"id":"S27","dim":"INF","text":"Vous voulez qu''un groupe adopte une idée nouvelle. Vous choisissez de :","o":{"A":"La présenter vous-même avec conviction en réunion clé.","B":"La faire porter progressivement par plusieurs membres respectés.","C":"La documenter formellement et la faire circuler par écrit.","D":"La tester d''abord en petit comité."},"w":{"A":[["INF",3]],"B":[["INF",3],["STR",1]],"C":[["INF",2]],"D":[["INF",2]]}}'::jsonb, 145),
  ('ntc-assessment', 5, 'mcq:S28', '{"id":"S28","dim":"MED","text":"Deux collaborateurs s''opposent frontalement devant vous. Vous :","o":{"A":"Tranchez immédiatement en faveur de celui qui a le plus raison.","B":"Laissez chacun exposer complètement son point de vue.","C":"Mettez fin à la discussion, mauvais moment.","D":"Proposez une pause pour que chacun revienne à froid."},"w":{"A":[["MED",-2]],"B":[["MED",3]],"C":[["MED",-3]],"D":[["MED",2]]}}'::jsonb, 146),
  ('ntc-assessment', 5, 'mcq:S29', '{"id":"S29","dim":"MED","text":"Un conflit entre deux collaborateurs dure depuis des semaines et affecte le reste de l''équipe. Vous :","o":{"A":"Laissez les deux le régler entre eux.","B":"Organisez une discussion structurée à trois pour clarifier les frictions.","C":"Séparez les deux sur des projets différents.","D":"Prenez parti pour celui que vous jugez avoir raison."},"w":{"A":[["MED",-3]],"B":[["MED",3]],"C":[["MED",-2]],"D":[["MED",-3]]}}'::jsonb, 147),
  ('ntc-assessment', 5, 'mcq:S30', '{"id":"S30","dim":"MED","text":"En médiation, l''une des deux parties devient nettement plus agressive verbalement. Vous :","o":{"A":"Recadrez fermement devant l''autre.","B":"Recadrez en privé avec la personne concernée.","C":"Laissez la discussion se poursuivre, ça va se calmer.","D":"Mettez fin à la médiation immédiatement."},"w":{"A":[["MED",2]],"B":[["MED",3]],"C":[["MED",-2]],"D":[["MED",-3]]}}'::jsonb, 148),
  ('ntc-assessment', 5, 'mcq:S31', '{"id":"S31","dim":"MED","text":"Après une médiation réussie en apparence, une partie ne semble pas pleinement satisfaite. Vous :","o":{"A":"Considérez le dossier clos.","B":"Reprenez contact individuellement pour vérifier son ressenti réel.","C":"Attendez de voir si le problème ressurgit.","D":"Demandez à l''autre partie si elle a remarqué la même chose."},"w":{"A":[["MED",-2]],"B":[["MED",3]],"C":[["MED",-1]],"D":[["MED",2]]}}'::jsonb, 149),
  ('ntc-assessment', 5, 'mcq:S32', '{"id":"S32","dim":"MED","text":"Vous devez médier un conflit alors que vous êtes proche de l''une des deux parties. Vous :","o":{"A":"Menez la médiation quand même.","B":"Passez la main à quelqu''un d''autre pour garantir l''impartialité perçue.","C":"Menez la médiation en le signalant explicitement aux deux parties.","D":"Évitez le sujet."},"w":{"A":[["MED",-2]],"B":[["MED",3]],"C":[["MED",2]],"D":[["MED",-3]]}}'::jsonb, 150),
  ('ntc-assessment', 6, 'mcq:P1', '{"id":"P1","dim":"STA","text":"Votre supérieur vous contredit publiquement, sur un point où vous êtes certain d''avoir raison. Vous :","o":{"A":"Répondez immédiatement pour rétablir les faits devant tout le monde.","B":"Restez posé et clarifiez le point en privé ensuite.","C":"Vous taisez complètement, même en privé par la suite.","D":"Changez d''avis publiquement pour ne pas prolonger la tension."},"w":{"A":[["STA",-2],["AFF",3]],"B":[["STA",3]],"C":[["STA",2],["AFF",-3]],"D":[["STA",-1],["AFF",-3]]}}'::jsonb, 151),
  ('ntc-assessment', 6, 'mcq:P2', '{"id":"P2","dim":"STA","text":"Un client vous crie dessus au téléphone pour une erreur qui n''est pas de votre fait. Vous :","o":{"A":"Restez calme et traitez le problème méthodiquement.","B":"Élevez la voix à votre tour.","C":"Raccrochez pour vous protéger.","D":"Vous excusez de façon excessive."},"w":{"A":[["STA",3]],"B":[["STA",-3],["IMP",3]],"C":[["STA",2]],"D":[["STA",2],["AFF",-3]]}}'::jsonb, 152),
  ('ntc-assessment', 6, 'mcq:P3', '{"id":"P3","dim":"STA","text":"Vous découvrez, en pleine réunion importante, une erreur significative dans un document que vous présentez. Vous :","o":{"A":"Continuez comme si de rien n''était, vous corrigerez après.","B":"Signalez calmement l''erreur et ajustez en direct.","C":"Paniquez visiblement et perdez le fil.","D":"Arrêtez la présentation pour tout reprendre à zéro."},"w":{"A":[["STA",2]],"B":[["STA",3],["AFF",2]],"C":[["STA",-3]],"D":[["STA",-2]]}}'::jsonb, 153),
  ('ntc-assessment', 6, 'mcq:P4', '{"id":"P4","dim":"STA","text":"Trois urgences arrivent en même temps, chacune réclamant votre attention immédiate. Vous :","o":{"A":"Traitez la première arrivée, dans l''ordre.","B":"Prenez 30 secondes pour évaluer laquelle est réellement la plus critique.","C":"Vous sentez dépassé, du mal à en traiter une seule correctement.","D":"Déléguez immédiatement les trois."},"w":{"A":[["STA",2]],"B":[["STA",3]],"C":[["STA",-3]],"D":[["STA",2]]}}'::jsonb, 154),
  ('ntc-assessment', 6, 'mcq:P5', '{"id":"P5","dim":"STA","text":"Une remarque désobligeante, en public, vous vise personnellement plutôt que votre travail. Vous :","o":{"A":"Répondez sur le même registre.","B":"Ne réagissez pas sur le moment, évaluez à froid comment répondre.","C":"Quittez la pièce pour éviter d''envenimer.","D":"Riez pour dédramatiser, même si ça vous a touché."},"w":{"A":[["STA",-3],["IMP",3]],"B":[["STA",3],["CTL",3]],"C":[["STA",2]],"D":[["STA",2],["CTL",-1]]}}'::jsonb, 155),
  ('ntc-assessment', 6, 'mcq:P6', '{"id":"P6","dim":"STA","text":"Après plusieurs jours de haute pression, une contrariété mineure déclenche une réaction disproportionnée. Vous :","o":{"A":"Laissez la réaction sortir, elle est légitime.","B":"Reconnaissez que la fatigue amplifie la réaction et ajustez.","C":"Vous isolez un moment avant de répondre.","D":"Reportez la contrariété sur la première personne disponible."},"w":{"A":[["STA",-2]],"B":[["STA",3]],"C":[["STA",2]],"D":[["STA",-3],["IMP",3]]}}'::jsonb, 156),
  ('ntc-assessment', 6, 'mcq:P7', '{"id":"P7","dim":"RES","text":"Un projet auquel vous avez consacré plusieurs mois est abandonné pour des raisons qui vous échappent en partie. Vous :","o":{"A":"Restez démobilisé plusieurs semaines sur vos projets suivants.","B":"Prenez le temps d''un vrai deuil du projet, puis vous remobilisez progressivement.","C":"Passez immédiatement au projet suivant sans y repenser.","D":"Cherchez systématiquement ce qui aurait pu être fait différemment, sans vous remobiliser tant que non résolu."},"w":{"A":[["RES",-3]],"B":[["RES",3]],"C":[["RES",2]],"D":[["RES",-1]]}}'::jsonb, 157),
  ('ntc-assessment', 6, 'mcq:P8', '{"id":"P8","dim":"RES","text":"Vous essuyez un refus important après plusieurs semaines de négociation. Vous :","o":{"A":"Considérez ce type de sujet clos pour l''avenir.","B":"Analysez ce qui a mené au refus, réutilisable pour la prochaine tentative.","C":"Retentez immédiatement, sans changer d''approche.","D":"Blâmez principalement des facteurs externes."},"w":{"A":[["RES",-3]],"B":[["RES",3]],"C":[["RES",2],["IMP",1]],"D":[["RES",-2]]}}'::jsonb, 158),
  ('ntc-assessment', 6, 'mcq:P9', '{"id":"P9","dim":"RES","text":"Une deuxième tentative sur un même type de projet échoue à nouveau. Vous :","o":{"A":"Continuez avec la même énergie qu''au premier essai.","B":"Prenez un recul plus long pour repenser fondamentalement l''approche.","C":"Abandonnez ce type de projet définitivement.","D":"Doutez fortement de votre capacité générale à réussir ce genre de choses."},"w":{"A":[["RES",3]],"B":[["RES",3]],"C":[["RES",-3]],"D":[["RES",-3]]}}'::jsonb, 159),
  ('ntc-assessment', 6, 'mcq:P10', '{"id":"P10","dim":"RES","text":"Retour très critique sur un travail dans lequel vous vous étiez beaucoup investi. Vous :","o":{"A":"Le prenez très mal sur le moment, mais vous en remettez rapidement.","B":"Le recevez avec du recul émotionnel, et l''utilisez pour progresser.","C":"Le contestez immédiatement point par point.","D":"Vous remettez en question bien au-delà de ce que justifie le retour."},"w":{"A":[["RES",2]],"B":[["RES",3]],"C":[["RES",2]],"D":[["RES",-3]]}}'::jsonb, 160),
  ('ntc-assessment', 6, 'mcq:P11', '{"id":"P11","dim":"RES","text":"Une période de plusieurs échecs consécutifs, sans lien direct entre eux, s''accumule. Vous :","o":{"A":"Continuez à un rythme inchangé.","B":"Faites une pause volontaire pour reprendre des forces.","C":"Accélérez le rythme pour compenser rapidement.","D":"Commencez à anticiper l''échec avant même de vous lancer."},"w":{"A":[["RES",2]],"B":[["RES",3]],"C":[["RES",-2],["IMP",1]],"D":[["RES",-3]]}}'::jsonb, 161),
  ('ntc-assessment', 6, 'mcq:P12', '{"id":"P12","dim":"RES","text":"Vous découvrez, des mois après, qu''une décision prise avec confiance a eu des conséquences plus importantes que prévu. Vous :","o":{"A":"L''assumez et en tirez des enseignements précis.","B":"Ressassez la décision de façon prolongée sans avancer.","C":"Minimisez l''ampleur réelle des conséquences.","D":"Redoublez de prudence excessive sur toutes vos décisions futures."},"w":{"A":[["RES",3]],"B":[["RES",-3]],"C":[["RES",2]],"D":[["RES",-2]]}}'::jsonb, 162),
  ('ntc-assessment', 6, 'mcq:P13', '{"id":"P13","dim":"IMP","text":"Vous recevez un message qui vous agace fortement. Vous :","o":{"A":"Répondez immédiatement, à chaud.","B":"Attendez au moins quelques heures avant de répondre.","C":"Rédigez une réponse à chaud mais attendez avant de l''envoyer.","D":"Ne répondez jamais aux messages qui vous agacent."},"w":{"A":[["IMP",3]],"B":[["IMP",-3],["CTL",3]],"C":[["IMP",2],["CTL",2]],"D":[["IMP",-2]]}}'::jsonb, 163),
  ('ntc-assessment', 6, 'mcq:P14', '{"id":"P14","dim":"IMP","text":"Une opportunité intéressante inattendue, réponse attendue dans l''heure. Vous :","o":{"A":"Décidez immédiatement selon votre premier ressenti.","B":"Prenez tout le temps disponible pour peser le pour et le contre.","C":"Décidez dans les 5 premières minutes, sans revenir dessus.","D":"Laissez passer l''opportunité plutôt que de décider trop vite."},"w":{"A":[["IMP",3]],"B":[["IMP",-3]],"C":[["IMP",2]],"D":[["IMP",-2]]}}'::jsonb, 164),
  ('ntc-assessment', 6, 'mcq:P15', '{"id":"P15","dim":"IMP","text":"Interrompu pour la cinquième fois dans la journée par la même personne, sujets mineurs à chaque fois. Vous :","o":{"A":"Le lui faites remarquer sèchement sur le moment.","B":"Continuez à répondre normalement, sans rien dire.","C":"Attendez un moment calme pour aborder le sujet posément.","D":"Devenez de plus en plus sec sans le dire ouvertement."},"w":{"A":[["IMP",3]],"B":[["IMP",-2]],"C":[["IMP",-3]],"D":[["IMP",2]]}}'::jsonb, 165),
  ('ntc-assessment', 6, 'mcq:P16', '{"id":"P16","dim":"IMP","text":"Une décision collective vient d''être prise, à laquelle vous étiez opposé. Une heure plus tard, nouvelle idée. Vous :","o":{"A":"Revenez immédiatement vers le groupe pour rouvrir le sujet.","B":"Laissez reposer l''idée un jour avant de décider si elle mérite d''être partagée.","C":"La gardez pour vous, la décision est prise.","D":"En parlez informellement à une seule personne d''abord."},"w":{"A":[["IMP",2]],"B":[["IMP",-3]],"C":[["IMP",-2]],"D":[["IMP",-2]]}}'::jsonb, 166),
  ('ntc-assessment', 6, 'mcq:P17', '{"id":"P17","dim":"IMP","text":"Vous constatez une erreur dans le travail d''un collègue juste avant une échéance critique. Vous :","o":{"A":"Le lui signalez immédiatement et fermement.","B":"Évaluez d''abord calmement l''impact réel avant d''intervenir.","C":"Corrigez l''erreur vous-même sans le prévenir.","D":"Attendez l''échéance pour voir si l''erreur a vraiment un impact."},"w":{"A":[["IMP",2]],"B":[["IMP",-3]],"C":[["IMP",3],["DEL",-1]],"D":[["IMP",-2]]}}'::jsonb, 167),
  ('ntc-assessment', 6, 'mcq:P18', '{"id":"P18","dim":"CTL","text":"Vous êtes profondément déçu par une décision, mais devez continuer à travailler normalement avec les personnes impliquées. Vous :","o":{"A":"Masquez complètement votre déception.","B":"Exprimez votre déception de façon mesurée, au bon moment.","C":"Laissez transparaître votre déception au quotidien.","D":"Évitez autant que possible les personnes impliquées."},"w":{"A":[["CTL",2]],"B":[["CTL",3]],"C":[["CTL",-3]],"D":[["CTL",-2]]}}'::jsonb, 168),
  ('ntc-assessment', 6, 'mcq:P19', '{"id":"P19","dim":"CTL","text":"Vous ressentez une forte irritation pendant une réunion, sans lien avec le sujet traité. Vous :","o":{"A":"La laissez influencer discrètement le ton de vos interventions.","B":"Prenez conscience de son origine et ajustez consciemment votre comportement.","C":"Quittez la réunion sous un prétexte pour vous recentrer.","D":"Ignorez complètement la sensation."},"w":{"A":[["CTL",-3]],"B":[["CTL",3]],"C":[["CTL",2]],"D":[["CTL",-2]]}}'::jsonb, 169),
  ('ntc-assessment', 6, 'mcq:P20', '{"id":"P20","dim":"CTL","text":"Une bonne nouvelle inattendue et importante arrive en pleine réunion sérieuse avec un partenaire externe. Vous :","o":{"A":"Exprimez votre enthousiasme immédiatement et pleinement.","B":"Notez intérieurement, maintenez le professionnalisme de la réunion en cours.","C":"Interrompez brièvement la réunion pour partager la nouvelle.","D":"Laissez la nouvelle vous distraire sans le montrer ouvertement."},"w":{"A":[["CTL",-2]],"B":[["CTL",3]],"C":[["CTL",-2]],"D":[["CTL",2]]}}'::jsonb, 170),
  ('ntc-assessment', 6, 'mcq:P21', '{"id":"P21","dim":"CTL","text":"Donner un feedback très négatif à quelqu''un pour qui vous avez beaucoup d''estime personnelle. Vous :","o":{"A":"Adoucissez fortement le message.","B":"Livrez le message avec clarté, respectueux du lien personnel.","C":"Reportez le feedback, la relation semble prioritaire.","D":"Livrez le message froidement, sans y mêler l''aspect personnel."},"w":{"A":[["CTL",2]],"B":[["CTL",3]],"C":[["CTL",-2]],"D":[["CTL",2]]}}'::jsonb, 171),
  ('ntc-assessment', 6, 'mcq:P22', '{"id":"P22","dim":"CTL","text":"Vous êtes témoin d''une injustice qui ne vous concerne pas directement, mais vous touche profondément. Vous :","o":{"A":"Intervenez immédiatement et fermement, sous le coup de l''indignation.","B":"Prenez un moment pour canaliser votre réaction avant de choisir comment intervenir.","C":"N''intervenez pas.","D":"Intervenez, mais de façon disproportionnée."},"w":{"A":[["CTL",-2]],"B":[["CTL",3]],"C":[["CTL",2]],"D":[["CTL",-3]]}}'::jsonb, 172),
  ('ntc-assessment', 6, 'mcq:P23', '{"id":"P23","dim":"CTL","text":"Rester concentré sur une tâche technique précise juste après une nouvelle personnelle préoccupante. Vous :","o":{"A":"Continuez la tâche normalement, en mettant la nouvelle de côté.","B":"Demandez un report ou de l''aide, votre concentration n''est pas fiable.","C":"Essayez de continuer, mais la qualité en pâtit sans que vous le remarquiez.","D":"Arrêtez tout net pour traiter la nouvelle en priorité."},"w":{"A":[["CTL",3]],"B":[["CTL",3]],"C":[["CTL",-2]],"D":[["CTL",-1]]}}'::jsonb, 173),
  ('ntc-assessment', 6, 'mcq:P24', '{"id":"P24","dim":"AFF","text":"On vous demande, en réunion, de valider rapidement une décision qui ne vous met pas à l''aise. Vous :","o":{"A":"Validez pour ne pas ralentir la réunion.","B":"Exprimez clairement votre réserve sur le moment.","C":"Restez silencieux.","D":"Demandez un report de la décision."},"w":{"A":[["AFF",-3]],"B":[["AFF",3]],"C":[["AFF",-3]],"D":[["AFF",2]]}}'::jsonb, 174),
  ('ntc-assessment', 6, 'mcq:P25', '{"id":"P25","dim":"AFF","text":"Un collègue vous attribue, par erreur ou mauvaise foi, la responsabilité d''un problème qui n''est pas le vôtre. Vous :","o":{"A":"Laissez dire, ça se clarifiera tout seul.","B":"Rétablissez les faits calmement et clairement.","C":"Contre-attaquez fermement.","D":"En parlez à d''autres personnes plutôt qu''à la personne concernée."},"w":{"A":[["AFF",-3]],"B":[["AFF",3]],"C":[["AFF",3]],"D":[["AFF",-2]]}}'::jsonb, 175),
  ('ntc-assessment', 6, 'mcq:P26', '{"id":"P26","dim":"AFF","text":"Votre charge de travail dépasse ce qui est soutenable, mais personne ne s''en rend compte. Vous :","o":{"A":"Continuez à absorber la charge sans le signaler.","B":"Signalez clairement la situation à qui de droit, avec des faits précis.","C":"Réduisez discrètement la qualité de certaines tâches sans le dire.","D":"Attendez le point de rupture pour que le problème devienne visible."},"w":{"A":[["AFF",-3]],"B":[["AFF",3]],"C":[["AFF",-2]],"D":[["AFF",-3]]}}'::jsonb, 176),
  ('ntc-assessment', 6, 'mcq:P27', '{"id":"P27","dim":"AFF","text":"Dire non à une demande de votre propre supérieur hiérarchique, pour une raison que vous jugez solide. Vous :","o":{"A":"Dites oui malgré tout.","B":"Dites non clairement, en expliquant votre raisonnement.","C":"Dites oui, mais exécutez a minima en signe de désaccord silencieux.","D":"Demandez un délai pour éviter de répondre non directement."},"w":{"A":[["AFF",-3]],"B":[["AFF",3]],"C":[["AFF",-3]],"D":[["AFF",-2]]}}'::jsonb, 177),
  ('ntc-assessment', 6, 'mcq:P28', '{"id":"P28","dim":"AFF","text":"Un groupe va clairement dans une direction risquée, vous êtes le seul à le percevoir. Vous :","o":{"A":"Exprimez votre point de vue fermement, même seul contre le groupe.","B":"Vous ralliez à la décision du groupe.","C":"Exprimez une réserve légère, sans insister.","D":"Gardez le silence et documentez votre désaccord pour vous."},"w":{"A":[["AFF",3]],"B":[["AFF",-3]],"C":[["AFF",2]],"D":[["AFF",-2]]}}'::jsonb, 178),
  ('ntc-assessment', 7, 'b7:C1', '{"id":"C1","text":"Vous prenez la direction d''une organisation de formation professionnelle de 500 personnes, en pleine croissance mais sans structure managériale intermédiaire solide. Quels sont vos trois premiers chantiers, et dans quel ordre ? Justifiez."}'::jsonb, 179),
  ('ntc-assessment', 7, 'b7:C2', '{"id":"C2","text":"Une organisation avec laquelle vous travaillez perd, en trois mois, 40 % de ses clients principaux au profit d''un concurrent moins cher mais de moindre qualité perçue. Que faites-vous, et pourquoi dans cet ordre ?"}'::jsonb, 180),
  ('ntc-assessment', 7, 'b7:C3', '{"id":"C3","text":"Vous dirigez une équipe de 15 personnes. Deux de vos meilleurs éléments menacent de partir si un troisième collaborateur, toléré depuis des années malgré des résultats médiocres, n''est pas recadré ou écarté. Comment abordez-vous la situation dans les 30 prochains jours ?"}'::jsonb, 181),
  ('ntc-assessment', 7, 'b7:C4', '{"id":"C4","text":"Votre organisation doit choisir entre ouvrir une nouvelle antenne dans une autre ville, ou approfondir son offre dans la ville actuelle. Potentiel comparable sur le papier. Comment structurez-vous votre décision ?"}'::jsonb, 182),
  ('ntc-assessment', 7, 'b7:C5', '{"id":"C5","text":"Une nouvelle technologie menace de rendre obsolète, d''ici 2-3 ans, une partie significative de votre modèle économique. Personne en interne n''est encore inquiet. Quelle est votre démarche sur les 6 prochains mois ?"}'::jsonb, 183),
  ('ntc-assessment', 7, 'b7:C6', '{"id":"C6","text":"Un partenaire majeur (50 % de votre activité) veut renégocier des conditions nettement moins favorables, sous peine de rupture. Deux semaines pour répondre. Comment structurez-vous votre réflexion et votre réponse ?"}'::jsonb, 184),
  ('ntc-assessment', 7, 'b7:C7', '{"id":"C7","text":"Vous héritez d''une équipe démotivée après un changement de direction précédent mal géré, turnover élevé sur 12 mois. 90 jours avant le prochain point d''étape avec votre hiérarchie. Que priorisez-vous ?"}'::jsonb, 185),
  ('ntc-assessment', 7, 'b7:C8', '{"id":"C8","text":"Un incident public ternit la réputation de votre organisation en 48h, couverture qui s''amplifie. Quelle est votre séquence d''action sur les premières 72h, puis sur les semaines suivantes ?"}'::jsonb, 186),
  ('ntc-assessment', 7, 'b7:C9', '{"id":"C9","text":"Votre organisation réussit au-delà des attentes, plusieurs pistes de diversification s''offrent simultanément. Le risque n''est plus l''échec mais la dispersion. Comment tranchez-vous ce qu''il faut faire, et surtout ne pas faire ?"}'::jsonb, 187),
  ('ntc-assessment', 8, 'b8:M1', '{"id":"M1","text":"100 000 € de budget, 10 collaborateurs, 3 mois pour lancer un service. Au bout de 6 semaines : départ du collaborateur clé + un client pilote qui menace de se retirer publiquement. Décrivez vos 7 premiers jours, puis le mois qui suit.","watch":["LDD","GCH","RES","STA","PRI","DIP","NST","RIS","CNF"]}'::jsonb, 188),
  ('ntc-assessment', 8, 'b8:M2', '{"id":"M2","text":"Un très bon élément vous informe, en confiance, qu''un collègue proche falsifie occasionnellement ses statistiques — et vous demande de ne rien faire, par loyauté. Décrivez votre gestion avec chacune des deux personnes.","watch":["INT","LOY","JUS","DIP","MED","COU","AFF"]}'::jsonb, 189),
  ('ntc-assessment', 8, 'b8:M3', '{"id":"M3","text":"48h pour choisir entre deux partenariats : l''un très avantageux financièrement mais avec droit de regard sur vos recrutements, l''autre moins avantageux mais préservant votre autonomie. Décrivez le processus, la décision, et l''annonce à l''équipe.","watch":["IS","PRA","RIG","RIS","NST","DIP"]}'::jsonb, 190),
  ('ntc-assessment', 8, 'b8:M4', '{"id":"M4","text":"Un collaborateur de confiance depuis 2 ans commet une erreur coûteuse, évitable en suivant une procédure connue. Décrivez l''échange à 48h, puis les décisions pour la suite.","watch":["JUS","CTL","SER","DIR","DIP","RES"]}'::jsonb, 191),
  ('ntc-assessment', 8, 'b8:M5', '{"id":"M5","text":"À 3 mois d''un jalon, retard significatif dû en partie à des facteurs externes et en partie à votre propre délégation insuffisante. Compte-rendu à votre hiérarchie dans une semaine. Décrivez comment vous le préparez et le menez.","watch":["INT","RES","AFF","CA","CNF"]}'::jsonb, 192),
  ('ntc-assessment', 8, 'b8:M6', '{"id":"M6","text":"Deux collaborateurs compétents en désaccord récurrent sur le traitement des clients difficiles, cohésion d''équipe affectée. 15 jours pour trancher une ligne commune. Décrivez votre démarche, puis comment vous la faites adopter sans braquer personne.","watch":["MED","CNS","LDD","DIP","VS"]}'::jsonb, 193),
  ('ntc-assessment', 8, 'b8:M7', '{"id":"M7","text":"Un investisseur potentiel veut vous rencontrer dans 3 jours, promesse de soutien significatif — rumeur d''une exclusivité attendue en retour, non confirmée. Décrivez votre préparation et ce que vous êtes prêt à céder ou non.","watch":["IS","NEG","RIS","AUT"]}'::jsonb, 194),
  ('ntc-assessment', 8, 'b8:M8', '{"id":"M8","text":"Échec collectif visible (client majeur perdu, lancement raté), moral bas, l''équipe attend une réaction claire. Décrivez vos 48 premières heures, puis le mois qui suit.","watch":["TRA","SER","RES","STA","DIP","NST"]}'::jsonb, 195),
  ('ntc-assessment', 8, 'b8:M9', '{"id":"M9","text":"Promotion attractive impliquant de superviser votre ancien mentor, qui traverse une période professionnelle difficile. Décrivez comment vous abordez la situation, avec lui et avec votre hiérarchie.","watch":["LOY","SER","DIP","CNF"]}'::jsonb, 196),
  ('ntc-assessment', 8, 'b8:M10', '{"id":"M10","text":"Vous découvrez qu''une décision stratégique portée avec conviction pendant des mois était probablement une erreur, les premiers résultats le confirment. Personne d''autre ne l''a reconnu explicitement. Décrivez vos semaines suivantes.","watch":["INT","RES","COU","CNF","CD"]}'::jsonb, 197);

-- ---------------------------------------------------------------------------
-- RLS : lecture du contenu pour authenticated (lignes actives uniquement) ;
-- aucune écriture front (service_role / SQL Editor seulement).
-- ---------------------------------------------------------------------------
alter table public.assessment_questions enable row level security;

drop policy if exists questions_select_authenticated on public.assessment_questions;
create policy questions_select_authenticated on public.assessment_questions
  for select to authenticated
  using (is_active = true);

-- Contrôles post-exécution (SQL Editor) :
--   select count(*) from public.assessment_questions;                    -- attendu : 197
--   select count(distinct question_id) from public.assessment_questions; -- attendu : 197
--   select battery_id, count(*) from public.assessment_questions group by battery_id order by battery_id;
-- Fin de migration P3-S9-1.
